// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL NOT BE MAINTAINED.

const std = @import("std");
const objc = @import("objc.zig"); // Objective-C Runtime in zig.
const core_foundation = @import("core_foundation.zig"); // Framework dependency CoreFoundation.
const core_audio_types = @import("core_audio_types.zig"); // Framework dependency CoreAudioTypes.

pub const ObjectID = objc.UInt32;

pub const ClassID = objc.UInt32;

pub const ObjectPropertySelector = objc.UInt32;

pub const ObjectPropertyScope = objc.UInt32;

pub const ObjectPropertyElement = objc.UInt32;

pub const ObjectPropertyAddress = extern struct {
    mSelector: ObjectPropertySelector,
    mScope: ObjectPropertyScope,
    mElement: ObjectPropertyElement,
};

pub const anon1521 = objc.OSStatus;
pub const anon1521_AudioHardwareNoError: objc.OSStatus = 0;
pub const anon1521_AudioHardwareNotRunningError: objc.OSStatus = 1937010544;
pub const anon1521_AudioHardwareUnspecifiedError: objc.OSStatus = 2003329396;
pub const anon1521_AudioHardwareUnknownPropertyError: objc.OSStatus = 2003332927;
pub const anon1521_AudioHardwareBadPropertySizeError: objc.OSStatus = 561211770;
pub const anon1521_AudioHardwareIllegalOperationError: objc.OSStatus = 1852797029;
pub const anon1521_AudioHardwareBadObjectError: objc.OSStatus = 560947818;
pub const anon1521_AudioHardwareBadDeviceError: objc.OSStatus = 560227702;
pub const anon1521_AudioHardwareBadStreamError: objc.OSStatus = 561214578;
pub const anon1521_AudioHardwareUnsupportedOperationError: objc.OSStatus = 1970171760;
pub const anon1521_AudioHardwareNotReadyError: objc.OSStatus = 1852990585;
pub const anon1521_AudioDeviceUnsupportedFormatError: objc.OSStatus = 560226676;
pub const anon1521_AudioDevicePermissionsError: objc.OSStatus = 560492391;

pub const anon1751 = ObjectID;
pub const anon1751_AudioObjectUnknown: ObjectID = 0;

pub const anon2011 = ObjectPropertyScope;
pub const anon2011_AudioObjectPropertyScopeGlobal: ObjectPropertyScope = 1735159650;
pub const anon2011_AudioObjectPropertyScopeInput: ObjectPropertyScope = 1768845428;
pub const anon2011_AudioObjectPropertyScopeOutput: ObjectPropertyScope = 1869968496;
pub const anon2011_AudioObjectPropertyScopePlayThrough: ObjectPropertyScope = 1886679669;
pub const anon2011_AudioObjectPropertyElementMain: ObjectPropertyScope = 0;
pub const anon2011_AudioObjectPropertyElementMaster: ObjectPropertyScope = 0;

pub const anon2251 = ObjectPropertySelector;
pub const anon2251_AudioObjectPropertySelectorWildcard: ObjectPropertySelector = 707406378;

pub const anon2301 = ObjectPropertyScope;
pub const anon2301_AudioObjectPropertyScopeWildcard: ObjectPropertyScope = 707406378;

pub const anon2351 = ObjectPropertyElement;
pub const anon2351_AudioObjectPropertyElementWildcard: ObjectPropertyElement = -1;

pub const anon2401 = ClassID;
pub const anon2401_AudioObjectClassIDWildcard: ClassID = 707406378;

pub const anon2561 = ClassID;
pub const anon2561_AudioObjectClassID: ClassID = 1634689642;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeScalar: ClassID = 1650620019;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeDecibels: ClassID = 1650620004;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeRangeDecibels: ClassID = 1650615331;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeScalarToDecibels: ClassID = 1651913316;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeDecibelsToScalar: ClassID = 1650733686;
pub const anon2561_AudioHardwarePropertyBootChimeVolumeDecibelsToScalarTransferFunction: ClassID = 1651930214;

pub const anon3291 = ObjectPropertySelector;
pub const anon3291_AudioObjectPropertyBaseClass: ObjectPropertySelector = 1650682995;
pub const anon3291_AudioObjectPropertyClass: ObjectPropertySelector = 1668047219;
pub const anon3291_AudioObjectPropertyOwner: ObjectPropertySelector = 1937007734;
pub const anon3291_AudioObjectPropertyName: ObjectPropertySelector = 1819173229;
pub const anon3291_AudioObjectPropertyModelName: ObjectPropertySelector = 1819111268;
pub const anon3291_AudioObjectPropertyManufacturer: ObjectPropertySelector = 1819107691;
pub const anon3291_AudioObjectPropertyElementName: ObjectPropertySelector = 1818454126;
pub const anon3291_AudioObjectPropertyElementCategoryName: ObjectPropertySelector = 1818452846;
pub const anon3291_AudioObjectPropertyElementNumberName: ObjectPropertySelector = 1818455662;
pub const anon3291_AudioObjectPropertyOwnedObjects: ObjectPropertySelector = 1870098020;
pub const anon3291_AudioObjectPropertyIdentify: ObjectPropertySelector = 1768187246;
pub const anon3291_AudioObjectPropertySerialNumber: ObjectPropertySelector = 1936618861;
pub const anon3291_AudioObjectPropertyFirmwareVersion: ObjectPropertySelector = 1719105134;

pub const anon3561 = ClassID;
pub const anon3561_AudioPlugInClassID: ClassID = 1634757735;

pub const anon4031 = ObjectPropertySelector;
pub const anon4031_AudioPlugInPropertyBundleID: ObjectPropertySelector = 1885956452;
pub const anon4031_AudioPlugInPropertyDeviceList: ObjectPropertySelector = 1684370979;
pub const anon4031_AudioPlugInPropertyTranslateUIDToDevice: ObjectPropertySelector = 1969841252;
pub const anon4031_AudioPlugInPropertyBoxList: ObjectPropertySelector = 1651472419;
pub const anon4031_AudioPlugInPropertyTranslateUIDToBox: ObjectPropertySelector = 1969841250;
pub const anon4031_AudioPlugInPropertyClockDeviceList: ObjectPropertySelector = 1668049699;
pub const anon4031_AudioPlugInPropertyTranslateUIDToClockDevice: ObjectPropertySelector = 1969841251;

pub const anon4301 = ClassID;
pub const anon4301_AudioTransportManagerClassID: ClassID = 1953656941;

pub const anon4601 = ObjectPropertySelector;
pub const anon4601_AudioTransportManagerPropertyEndPointList: ObjectPropertySelector = 1701733411;
pub const anon4601_AudioTransportManagerPropertyTranslateUIDToEndPoint: ObjectPropertySelector = 1969841253;
pub const anon4601_AudioTransportManagerPropertyTransportType: ObjectPropertySelector = 1953653102;

pub const anon4771 = ClassID;
pub const anon4771_AudioBoxClassID: ClassID = 1633841016;

pub const anon5291 = ObjectPropertySelector;
pub const anon5291_AudioBoxPropertyBoxUID: ObjectPropertySelector = 1651861860;
pub const anon5291_AudioBoxPropertyTransportType: ObjectPropertySelector = 1953653102;
pub const anon5291_AudioBoxPropertyHasAudio: ObjectPropertySelector = 1651007861;
pub const anon5291_AudioBoxPropertyHasVideo: ObjectPropertySelector = 1651013225;
pub const anon5291_AudioBoxPropertyHasMIDI: ObjectPropertySelector = 1651010921;
pub const anon5291_AudioBoxPropertyIsProtected: ObjectPropertySelector = 1651536495;
pub const anon5291_AudioBoxPropertyAcquired: ObjectPropertySelector = 1652060014;
pub const anon5291_AudioBoxPropertyAcquisitionFailed: ObjectPropertySelector = 1652060006;
pub const anon5291_AudioBoxPropertyDeviceList: ObjectPropertySelector = 1650751011;
pub const anon5291_AudioBoxPropertyClockDeviceList: ObjectPropertySelector = 1650682915;

pub const anon5531 = ClassID;
pub const anon5531_AudioDeviceClassID: ClassID = 1633969526;

pub const anon6071 = objc.UInt32;
pub const anon6071_AudioDeviceTransportTypeUnknown: objc.UInt32 = 0;
pub const anon6071_AudioDeviceTransportTypeBuiltIn: objc.UInt32 = 1651274862;
pub const anon6071_AudioDeviceTransportTypeAggregate: objc.UInt32 = 1735554416;
pub const anon6071_AudioDeviceTransportTypeVirtual: objc.UInt32 = 1986622068;
pub const anon6071_AudioDeviceTransportTypePCI: objc.UInt32 = 1885563168;
pub const anon6071_AudioDeviceTransportTypeUSB: objc.UInt32 = 1970496032;
pub const anon6071_AudioDeviceTransportTypeFireWire: objc.UInt32 = 825440564;
pub const anon6071_AudioDeviceTransportTypeBluetooth: objc.UInt32 = 1651275109;
pub const anon6071_AudioDeviceTransportTypeBluetoothLE: objc.UInt32 = 1651271009;
pub const anon6071_AudioDeviceTransportTypeHDMI: objc.UInt32 = 1751412073;
pub const anon6071_AudioDeviceTransportTypeDisplayPort: objc.UInt32 = 1685090932;
pub const anon6071_AudioDeviceTransportTypeAirPlay: objc.UInt32 = 1634300528;
pub const anon6071_AudioDeviceTransportTypeAVB: objc.UInt32 = 1700886114;
pub const anon6071_AudioDeviceTransportTypeThunderbolt: objc.UInt32 = 1953002862;
pub const anon6071_AudioDeviceTransportTypeContinuityCaptureWired: objc.UInt32 = 1667463012;
pub const anon6071_AudioDeviceTransportTypeContinuityCaptureWireless: objc.UInt32 = 1667463020;
pub const anon6071_AudioDeviceTransportTypeContinuityCapture: objc.UInt32 = 1667457392;

pub const anon7311 = ObjectPropertySelector;
pub const anon7311_AudioDevicePropertyConfigurationApplication: ObjectPropertySelector = 1667330160;
pub const anon7311_AudioDevicePropertyDeviceUID: ObjectPropertySelector = 1969841184;
pub const anon7311_AudioDevicePropertyModelUID: ObjectPropertySelector = 1836411236;
pub const anon7311_AudioDevicePropertyTransportType: ObjectPropertySelector = 1953653102;
pub const anon7311_AudioDevicePropertyRelatedDevices: ObjectPropertySelector = 1634429294;
pub const anon7311_AudioDevicePropertyClockDomain: ObjectPropertySelector = 1668049764;
pub const anon7311_AudioDevicePropertyDeviceIsAlive: ObjectPropertySelector = 1818850926;
pub const anon7311_AudioDevicePropertyDeviceIsRunning: ObjectPropertySelector = 1735354734;
pub const anon7311_AudioDevicePropertyDeviceCanBeDefaultDevice: ObjectPropertySelector = 1684434036;
pub const anon7311_AudioDevicePropertyDeviceCanBeDefaultSystemDevice: ObjectPropertySelector = 1936092276;
pub const anon7311_AudioDevicePropertyLatency: ObjectPropertySelector = 1819569763;
pub const anon7311_AudioDevicePropertyStreams: ObjectPropertySelector = 1937009955;
pub const anon7311_AudioObjectPropertyControlList: ObjectPropertySelector = 1668575852;
pub const anon7311_AudioDevicePropertySafetyOffset: ObjectPropertySelector = 1935763060;
pub const anon7311_AudioDevicePropertyNominalSampleRate: ObjectPropertySelector = 1853059700;
pub const anon7311_AudioDevicePropertyAvailableNominalSampleRates: ObjectPropertySelector = 1853059619;
pub const anon7311_AudioDevicePropertyIcon: ObjectPropertySelector = 1768124270;
pub const anon7311_AudioDevicePropertyIsHidden: ObjectPropertySelector = 1751737454;
pub const anon7311_AudioDevicePropertyPreferredChannelsForStereo: ObjectPropertySelector = 1684236338;
pub const anon7311_AudioDevicePropertyPreferredChannelLayout: ObjectPropertySelector = 1936879204;

pub const anon7651 = ObjectPropertySelector;
pub const anon7651_AudioClockDeviceClassID: ObjectPropertySelector = 1633905771;

pub const anon8181 = ObjectPropertySelector;
pub const anon8181_AudioClockDevicePropertyDeviceUID: ObjectPropertySelector = 1668639076;
pub const anon8181_AudioClockDevicePropertyTransportType: ObjectPropertySelector = 1953653102;
pub const anon8181_AudioClockDevicePropertyClockDomain: ObjectPropertySelector = 1668049764;
pub const anon8181_AudioClockDevicePropertyDeviceIsAlive: ObjectPropertySelector = 1818850926;
pub const anon8181_AudioClockDevicePropertyDeviceIsRunning: ObjectPropertySelector = 1735354734;
pub const anon8181_AudioClockDevicePropertyLatency: ObjectPropertySelector = 1819569763;
pub const anon8181_AudioClockDevicePropertyControlList: ObjectPropertySelector = 1668575852;
pub const anon8181_AudioClockDevicePropertyNominalSampleRate: ObjectPropertySelector = 1853059700;
pub const anon8181_AudioClockDevicePropertyAvailableNominalSampleRates: ObjectPropertySelector = 1853059619;

pub const anon8401 = ClassID;
pub const anon8401_AudioEndPointDeviceClassID: ClassID = 1701078390;

pub const anon9161 = ObjectPropertySelector;
pub const anon9161_AudioEndPointDevicePropertyComposition: ObjectPropertySelector = 1633906541;
pub const anon9161_AudioEndPointDevicePropertyEndPointList: ObjectPropertySelector = 1634169456;
pub const anon9161_AudioEndPointDevicePropertyIsPrivate: ObjectPropertySelector = 1886546294;

pub const anon9371 = ClassID;
pub const anon9371_AudioEndPointClassID: ClassID = 1701733488;
pub const anon9371_AudioAggregateDevicePropertyMasterSubDevice: ClassID = 1634562932;

pub const StreamRangedDescription = extern struct {
    mFormat: core_audio_types.StreamBasicDescription,
    mSampleRateRange: core_audio_types.ValueRange,
};

pub const anon10151 = ClassID;
pub const anon10151_AudioStreamClassID: ClassID = 1634956402;

pub const anon10531 = objc.UInt32;
pub const anon10531_AudioStreamTerminalTypeUnknown: objc.UInt32 = 0;
pub const anon10531_AudioStreamTerminalTypeLine: objc.UInt32 = 1818848869;
pub const anon10531_AudioStreamTerminalTypeDigitalAudioInterface: objc.UInt32 = 1936745574;
pub const anon10531_AudioStreamTerminalTypeSpeaker: objc.UInt32 = 1936747378;
pub const anon10531_AudioStreamTerminalTypeHeadphones: objc.UInt32 = 1751412840;
pub const anon10531_AudioStreamTerminalTypeLFESpeaker: objc.UInt32 = 1818649971;
pub const anon10531_AudioStreamTerminalTypeReceiverSpeaker: objc.UInt32 = 1920168043;
pub const anon10531_AudioStreamTerminalTypeMicrophone: objc.UInt32 = 1835623282;
pub const anon10531_AudioStreamTerminalTypeHeadsetMicrophone: objc.UInt32 = 1752000867;
pub const anon10531_AudioStreamTerminalTypeReceiverMicrophone: objc.UInt32 = 1919773027;
pub const anon10531_AudioStreamTerminalTypeTTY: objc.UInt32 = 1953790303;
pub const anon10531_AudioStreamTerminalTypeHDMI: objc.UInt32 = 1751412073;
pub const anon10531_AudioStreamTerminalTypeDisplayPort: objc.UInt32 = 1685090932;

pub const anon11151 = ObjectPropertySelector;
pub const anon11151_AudioStreamPropertyIsActive: ObjectPropertySelector = 1935762292;
pub const anon11151_AudioStreamPropertyDirection: ObjectPropertySelector = 1935960434;
pub const anon11151_AudioStreamPropertyTerminalType: ObjectPropertySelector = 1952805485;
pub const anon11151_AudioStreamPropertyStartingChannel: ObjectPropertySelector = 1935894638;
pub const anon11151_AudioStreamPropertyLatency: ObjectPropertySelector = 1819569763;
pub const anon11151_AudioStreamPropertyVirtualFormat: ObjectPropertySelector = 1936092532;
pub const anon11151_AudioStreamPropertyAvailableVirtualFormats: ObjectPropertySelector = 1936092513;
pub const anon11151_AudioStreamPropertyPhysicalFormat: ObjectPropertySelector = 1885762592;
pub const anon11151_AudioStreamPropertyAvailablePhysicalFormats: ObjectPropertySelector = 1885762657;

pub const anon11371 = ClassID;
pub const anon11371_AudioControlClassID: ClassID = 1633907820;

pub const anon11551 = ObjectPropertySelector;
pub const anon11551_AudioControlPropertyScope: ObjectPropertySelector = 1668506480;
pub const anon11551_AudioControlPropertyElement: ObjectPropertySelector = 1667591277;

pub const anon11711 = ClassID;
pub const anon11711_AudioSliderControlClassID: ClassID = 1936483442;

pub const anon11871 = ObjectPropertySelector;
pub const anon11871_AudioSliderControlPropertyValue: ObjectPropertySelector = 1935962742;
pub const anon11871_AudioSliderControlPropertyRange: ObjectPropertySelector = 1935962738;

pub const anon12101 = ClassID;
pub const anon12101_AudioLevelControlClassID: ClassID = 1818588780;
pub const anon12101_AudioVolumeControlClassID: ClassID = 1986817381;
pub const anon12101_AudioLFEVolumeControlClassID: ClassID = 1937072758;

pub const anon12471 = ObjectPropertySelector;
pub const anon12471_AudioLevelControlPropertyScalarValue: ObjectPropertySelector = 1818456950;
pub const anon12471_AudioLevelControlPropertyDecibelValue: ObjectPropertySelector = 1818453110;
pub const anon12471_AudioLevelControlPropertyDecibelRange: ObjectPropertySelector = 1818453106;
pub const anon12471_AudioLevelControlPropertyConvertScalarToDecibels: ObjectPropertySelector = 1818456932;
pub const anon12471_AudioLevelControlPropertyConvertDecibelsToScalar: ObjectPropertySelector = 1818453107;

pub const anon13021 = ClassID;
pub const anon13021_AudioBooleanControlClassID: ClassID = 1953458028;
pub const anon13021_AudioMuteControlClassID: ClassID = 1836414053;
pub const anon13021_AudioSoloControlClassID: ClassID = 1936682095;
pub const anon13021_AudioJackControlClassID: ClassID = 1784767339;
pub const anon13021_AudioLFEMuteControlClassID: ClassID = 1937072749;
pub const anon13021_AudioPhantomPowerControlClassID: ClassID = 1885888878;
pub const anon13021_AudioPhaseInvertControlClassID: ClassID = 1885893481;
pub const anon13021_AudioClipLightControlClassID: ClassID = 1668049264;
pub const anon13021_AudioTalkbackControlClassID: ClassID = 1952541794;
pub const anon13021_AudioListenbackControlClassID: ClassID = 1819504226;

pub const anon13241 = ObjectPropertySelector;
pub const anon13241_AudioBooleanControlPropertyValue: ObjectPropertySelector = 1650685548;

pub const anon13561 = ClassID;
pub const anon13561_AudioSelectorControlClassID: ClassID = 1936483188;
pub const anon13561_AudioDataSourceControlClassID: ClassID = 1685287523;
pub const anon13561_AudioDataDestinationControlClassID: ClassID = 1684370292;
pub const anon13561_AudioClockSourceControlClassID: ClassID = 1668047723;
pub const anon13561_AudioLineLevelControlClassID: ClassID = 1852601964;
pub const anon13561_AudioHighPassFilterControlClassID: ClassID = 1751740518;

pub const anon13861 = ObjectPropertySelector;
pub const anon13861_AudioSelectorControlPropertyCurrentItem: ObjectPropertySelector = 1935893353;
pub const anon13861_AudioSelectorControlPropertyAvailableItems: ObjectPropertySelector = 1935892841;
pub const anon13861_AudioSelectorControlPropertyItemName: ObjectPropertySelector = 1935894894;
pub const anon13861_AudioSelectorControlPropertyItemKind: ObjectPropertySelector = 1668049771;

pub const anon14011 = objc.UInt32;
pub const anon14011_AudioSelectorControlItemKindSpacer: objc.UInt32 = 1936745330;

pub const anon14121 = objc.UInt32;
pub const anon14121_AudioClockSourceItemKindInternal: objc.UInt32 = 1768846368;

pub const anon14271 = ClassID;
pub const anon14271_AudioStereoPanControlClassID: ClassID = 1936744814;

pub const anon14431 = ObjectPropertySelector;
pub const anon14431_AudioStereoPanControlPropertyValue: ObjectPropertySelector = 1936745334;
pub const anon14431_AudioStereoPanControlPropertyPanningChannels: ObjectPropertySelector = 1936745315;

pub const anon1081 = i32;
pub const anon1081_AudioObjectSystemObject: i32 = 1;

pub const ObjectPropertyListenerProc = objc.OSStatus;

pub const ObjectPropertyListenerBlock = *const fn (objc.UInt32, ?*const ObjectPropertyAddress) callconv(.C) void;

pub const anon1871 = ObjectPropertySelector;
pub const anon1871_AudioObjectPropertyCreator: ObjectPropertySelector = 1869638759;
pub const anon1871_AudioObjectPropertyListenerAdded: ObjectPropertySelector = 1818850145;
pub const anon1871_AudioObjectPropertyListenerRemoved: ObjectPropertySelector = 1818850162;

extern "CoreAudio" fn AudioObjectShow(inObjectID: ObjectID) callconv(.C) void;
pub const objectShow = AudioObjectShow;

extern "CoreAudio" fn AudioObjectHasProperty(inObjectID: ObjectID, inAddress: ?*const ObjectPropertyAddress) callconv(.C) objc.Boolean;
pub const objectHasProperty = AudioObjectHasProperty;

extern "CoreAudio" fn AudioObjectIsPropertySettable(inObjectID: ObjectID, inAddress: ?*const ObjectPropertyAddress, outIsSettable: ?*objc.Boolean) callconv(.C) objc.OSStatus;
pub const objectIsPropertySettable = AudioObjectIsPropertySettable;

extern "CoreAudio" fn AudioObjectGetPropertyDataSize(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inQualifierDataSize: objc.UInt32,
    inQualifierData: ?*const anyopaque,
    outDataSize: ?*objc.UInt32,
) callconv(.C) objc.OSStatus;
pub const objectGetPropertyDataSize = AudioObjectGetPropertyDataSize;

extern "CoreAudio" fn AudioObjectGetPropertyData(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inQualifierDataSize: objc.UInt32,
    inQualifierData: ?*const anyopaque,
    ioDataSize: ?*objc.UInt32,
    outData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const objectGetPropertyData = AudioObjectGetPropertyData;

extern "CoreAudio" fn AudioObjectSetPropertyData(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inQualifierDataSize: objc.UInt32,
    inQualifierData: ?*const anyopaque,
    inDataSize: objc.UInt32,
    inData: ?*const anyopaque,
) callconv(.C) objc.OSStatus;
pub const objectSetPropertyData = AudioObjectSetPropertyData;

extern "CoreAudio" fn AudioObjectAddPropertyListener(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inListener: ObjectPropertyListenerProc,
    inClientData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const objectAddPropertyListener = AudioObjectAddPropertyListener;

extern "CoreAudio" fn AudioObjectRemovePropertyListener(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inListener: ObjectPropertyListenerProc,
    inClientData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const objectRemovePropertyListener = AudioObjectRemovePropertyListener;

extern "CoreAudio" fn AudioObjectAddPropertyListenerBlock(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inDispatchQueue: objc.dispatch_queue_t,
    inListener: ObjectPropertyListenerBlock,
) callconv(.C) objc.OSStatus;
pub const objectAddPropertyListenerBlock = AudioObjectAddPropertyListenerBlock;

extern "CoreAudio" fn AudioObjectRemovePropertyListenerBlock(
    inObjectID: ObjectID,
    inAddress: ?*const ObjectPropertyAddress,
    inDispatchQueue: objc.dispatch_queue_t,
    inListener: ObjectPropertyListenerBlock,
) callconv(.C) objc.OSStatus;
pub const objectRemovePropertyListenerBlock = AudioObjectRemovePropertyListenerBlock;

pub const anon4351 = ClassID;
pub const anon4351_AudioSystemObjectClassID: ClassID = 1634957683;

pub const HardwarePowerHint = objc.UInt32;
pub const HardwarePowerHint_None: objc.UInt32 = 0;
pub const HardwarePowerHint_FavorSavingPower: objc.UInt32 = 1;

pub const anon6061 = ObjectPropertySelector;
pub const anon6061_AudioHardwarePropertyDevices: ObjectPropertySelector = 1684370979;
pub const anon6061_AudioHardwarePropertyDefaultInputDevice: ObjectPropertySelector = 1682533920;
pub const anon6061_AudioHardwarePropertyDefaultOutputDevice: ObjectPropertySelector = 1682929012;
pub const anon6061_AudioHardwarePropertyDefaultSystemOutputDevice: ObjectPropertySelector = 1934587252;
pub const anon6061_AudioHardwarePropertyTranslateUIDToDevice: ObjectPropertySelector = 1969841252;
pub const anon6061_AudioHardwarePropertyMixStereoToMono: ObjectPropertySelector = 1937010031;
pub const anon6061_AudioHardwarePropertyPlugInList: ObjectPropertySelector = 1886152483;
pub const anon6061_AudioHardwarePropertyTranslateBundleIDToPlugIn: ObjectPropertySelector = 1651074160;
pub const anon6061_AudioHardwarePropertyTransportManagerList: ObjectPropertySelector = 1953326883;
pub const anon6061_AudioHardwarePropertyTranslateBundleIDToTransportManager: ObjectPropertySelector = 1953325673;
pub const anon6061_AudioHardwarePropertyBoxList: ObjectPropertySelector = 1651472419;
pub const anon6061_AudioHardwarePropertyTranslateUIDToBox: ObjectPropertySelector = 1969841250;
pub const anon6061_AudioHardwarePropertyClockDeviceList: ObjectPropertySelector = 1668049699;
pub const anon6061_AudioHardwarePropertyTranslateUIDToClockDevice: ObjectPropertySelector = 1969841251;
pub const anon6061_AudioHardwarePropertyProcessIsMain: ObjectPropertySelector = 1835100526;
pub const anon6061_AudioHardwarePropertyIsInitingOrExiting: ObjectPropertySelector = 1768845172;
pub const anon6061_AudioHardwarePropertyUserIDChanged: ObjectPropertySelector = 1702193508;
pub const anon6061_AudioHardwarePropertyProcessInputMute: ObjectPropertySelector = 1886218606;
pub const anon6061_AudioHardwarePropertyProcessIsAudible: ObjectPropertySelector = 1886221684;
pub const anon6061_AudioHardwarePropertySleepingIsAllowed: ObjectPropertySelector = 1936483696;
pub const anon6061_AudioHardwarePropertyUnloadingIsAllowed: ObjectPropertySelector = 1970170980;
pub const anon6061_AudioHardwarePropertyHogModeIsAllowed: ObjectPropertySelector = 1752131442;
pub const anon6061_AudioHardwarePropertyUserSessionIsActiveOrHeadless: ObjectPropertySelector = 1970496882;
pub const anon6061_AudioHardwarePropertyServiceRestarted: ObjectPropertySelector = 1936880500;
pub const anon6061_AudioHardwarePropertyPowerHint: ObjectPropertySelector = 1886353256;
pub const anon6061_AudioHardwarePropertyProcessObjectList: ObjectPropertySelector = 1886548771;
pub const anon6061_AudioHardwarePropertyTranslatePIDToProcessObject: ObjectPropertySelector = 1768174192;
pub const anon6061_AudioHardwarePropertyTapList: ObjectPropertySelector = 1953526563;
pub const anon6061_AudioHardwarePropertyTranslateUIDToTap: ObjectPropertySelector = 1969841268;

extern "CoreAudio" fn AudioHardwareUnload() callconv(.C) objc.OSStatus;
pub const hardwareUnload = AudioHardwareUnload;

extern "CoreAudio" fn AudioHardwareCreateAggregateDevice(inDescription: core_foundation.DictionaryRef, outDeviceID: ?*ObjectID) callconv(.C) objc.OSStatus;
pub const hardwareCreateAggregateDevice = AudioHardwareCreateAggregateDevice;

extern "CoreAudio" fn AudioHardwareDestroyAggregateDevice(inDeviceID: ObjectID) callconv(.C) objc.OSStatus;
pub const hardwareDestroyAggregateDevice = AudioHardwareDestroyAggregateDevice;

pub const anon7041 = ObjectPropertySelector;
pub const anon7041_AudioPlugInCreateAggregateDevice: ObjectPropertySelector = 1667327847;
pub const anon7041_AudioPlugInDestroyAggregateDevice: ObjectPropertySelector = 1684105063;

pub const anon7331 = ObjectPropertySelector;
pub const anon7331_AudioTransportManagerCreateEndPointDevice: ObjectPropertySelector = 1667523958;
pub const anon7331_AudioTransportManagerDestroyEndPointDevice: ObjectPropertySelector = 1684301174;

pub const DeviceIOProc = objc.OSStatus;

pub const DeviceIOBlock = *const fn (
    ?*const core_audio_types.TimeStamp,
    ?*const core_audio_types.BufferList,
    ?*const core_audio_types.TimeStamp,
    ?*core_audio_types.BufferList,
    ?*const core_audio_types.TimeStamp,
) callconv(.C) void;

pub const DeviceIOProcID = DeviceIOProc;

pub const HardwareIOProcStreamUsage = extern struct {
    mIOProc: ?*anyopaque,
    mNumberStreams: objc.UInt32,
    mStreamIsOn: [1]objc.UInt32,
};

pub const anon8881 = objc.UInt32;
pub const anon8881_AudioDeviceStartTimeIsInputFlag: objc.UInt32 = 1;
pub const anon8881_AudioDeviceStartTimeDontConsultDeviceFlag: objc.UInt32 = 2;
pub const anon8881_AudioDeviceStartTimeDontConsultHALFlag: objc.UInt32 = 4;

pub const anon9961 = ObjectPropertySelector;
pub const anon9961_AudioDevicePropertyPlugIn: ObjectPropertySelector = 1886156135;
pub const anon9961_AudioDevicePropertyDeviceHasChanged: ObjectPropertySelector = 1684629094;
pub const anon9961_AudioDevicePropertyDeviceIsRunningSomewhere: ObjectPropertySelector = 1735356005;
pub const anon9961_AudioDeviceProcessorOverload: ObjectPropertySelector = 1870030194;
pub const anon9961_AudioDevicePropertyIOStoppedAbnormally: ObjectPropertySelector = 1937010788;
pub const anon9961_AudioDevicePropertyHogMode: ObjectPropertySelector = 1869180523;
pub const anon9961_AudioDevicePropertyBufferFrameSize: ObjectPropertySelector = 1718839674;
pub const anon9961_AudioDevicePropertyBufferFrameSizeRange: ObjectPropertySelector = 1718843939;
pub const anon9961_AudioDevicePropertyUsesVariableBufferFrameSizes: ObjectPropertySelector = 1986425722;
pub const anon9961_AudioDevicePropertyIOCycleUsage: ObjectPropertySelector = 1852012899;
pub const anon9961_AudioDevicePropertyStreamConfiguration: ObjectPropertySelector = 1936482681;
pub const anon9961_AudioDevicePropertyIOProcStreamUsage: ObjectPropertySelector = 1937077093;
pub const anon9961_AudioDevicePropertyActualSampleRate: ObjectPropertySelector = 1634955892;
pub const anon9961_AudioDevicePropertyClockDevice: ObjectPropertySelector = 1634755428;
pub const anon9961_AudioDevicePropertyIOThreadOSWorkgroup: ObjectPropertySelector = 1869838183;
pub const anon9961_AudioDevicePropertyProcessMute: ObjectPropertySelector = 1634758765;

pub const anon12891 = ObjectPropertySelector;
pub const anon12891_AudioDevicePropertyJackIsConnected: ObjectPropertySelector = 1784767339;
pub const anon12891_AudioDevicePropertyVolumeScalar: ObjectPropertySelector = 1987013741;
pub const anon12891_AudioDevicePropertyVolumeDecibels: ObjectPropertySelector = 1987013732;
pub const anon12891_AudioDevicePropertyVolumeRangeDecibels: ObjectPropertySelector = 1986290211;
pub const anon12891_AudioDevicePropertyVolumeScalarToDecibels: ObjectPropertySelector = 1983013986;
pub const anon12891_AudioDevicePropertyVolumeDecibelsToScalar: ObjectPropertySelector = 1684157046;
pub const anon12891_AudioDevicePropertyStereoPan: ObjectPropertySelector = 1936744814;
pub const anon12891_AudioDevicePropertyStereoPanChannels: ObjectPropertySelector = 1936748067;
pub const anon12891_AudioDevicePropertyMute: ObjectPropertySelector = 1836414053;
pub const anon12891_AudioDevicePropertySolo: ObjectPropertySelector = 1936682095;
pub const anon12891_AudioDevicePropertyPhantomPower: ObjectPropertySelector = 1885888878;
pub const anon12891_AudioDevicePropertyPhaseInvert: ObjectPropertySelector = 1885893481;
pub const anon12891_AudioDevicePropertyClipLight: ObjectPropertySelector = 1668049264;
pub const anon12891_AudioDevicePropertyTalkback: ObjectPropertySelector = 1952541794;
pub const anon12891_AudioDevicePropertyListenback: ObjectPropertySelector = 1819504226;
pub const anon12891_AudioDevicePropertyDataSource: ObjectPropertySelector = 1936945763;
pub const anon12891_AudioDevicePropertyDataSources: ObjectPropertySelector = 1936941859;
pub const anon12891_AudioDevicePropertyDataSourceNameForIDCFString: ObjectPropertySelector = 1819501422;
pub const anon12891_AudioDevicePropertyDataSourceKindForID: ObjectPropertySelector = 1936941931;
pub const anon12891_AudioDevicePropertyClockSource: ObjectPropertySelector = 1668510307;
pub const anon12891_AudioDevicePropertyClockSources: ObjectPropertySelector = 1668506403;
pub const anon12891_AudioDevicePropertyClockSourceNameForIDCFString: ObjectPropertySelector = 1818456942;
pub const anon12891_AudioDevicePropertyClockSourceKindForID: ObjectPropertySelector = 1668506475;
pub const anon12891_AudioDevicePropertyPlayThru: ObjectPropertySelector = 1953002101;
pub const anon12891_AudioDevicePropertyPlayThruSolo: ObjectPropertySelector = 1953002099;
pub const anon12891_AudioDevicePropertyPlayThruVolumeScalar: ObjectPropertySelector = 1836479331;
pub const anon12891_AudioDevicePropertyPlayThruVolumeDecibels: ObjectPropertySelector = 1836475490;
pub const anon12891_AudioDevicePropertyPlayThruVolumeRangeDecibels: ObjectPropertySelector = 1836475427;
pub const anon12891_AudioDevicePropertyPlayThruVolumeScalarToDecibels: ObjectPropertySelector = 1836462692;
pub const anon12891_AudioDevicePropertyPlayThruVolumeDecibelsToScalar: ObjectPropertySelector = 1836462707;
pub const anon12891_AudioDevicePropertyPlayThruStereoPan: ObjectPropertySelector = 1836281966;
pub const anon12891_AudioDevicePropertyPlayThruStereoPanChannels: ObjectPropertySelector = 1836281891;
pub const anon12891_AudioDevicePropertyPlayThruDestination: ObjectPropertySelector = 1835295859;
pub const anon12891_AudioDevicePropertyPlayThruDestinations: ObjectPropertySelector = 1835295779;
pub const anon12891_AudioDevicePropertyPlayThruDestinationNameForIDCFString: ObjectPropertySelector = 1835295843;
pub const anon12891_AudioDevicePropertyChannelNominalLineLevel: ObjectPropertySelector = 1852601964;
pub const anon12891_AudioDevicePropertyChannelNominalLineLevels: ObjectPropertySelector = 1852601891;
pub const anon12891_AudioDevicePropertyChannelNominalLineLevelNameForIDCFString: ObjectPropertySelector = 1818455660;
pub const anon12891_AudioDevicePropertyHighPassFilterSetting: ObjectPropertySelector = 1751740518;
pub const anon12891_AudioDevicePropertyHighPassFilterSettings: ObjectPropertySelector = 1751740451;
pub const anon12891_AudioDevicePropertyHighPassFilterSettingNameForIDCFString: ObjectPropertySelector = 1751740524;
pub const anon12891_AudioDevicePropertySubVolumeScalar: ObjectPropertySelector = 1937140845;
pub const anon12891_AudioDevicePropertySubVolumeDecibels: ObjectPropertySelector = 1937140836;
pub const anon12891_AudioDevicePropertySubVolumeRangeDecibels: ObjectPropertySelector = 1937138723;
pub const anon12891_AudioDevicePropertySubVolumeScalarToDecibels: ObjectPropertySelector = 1937125988;
pub const anon12891_AudioDevicePropertySubVolumeDecibelsToScalar: ObjectPropertySelector = 1935946358;
pub const anon12891_AudioDevicePropertySubMute: ObjectPropertySelector = 1936553332;
pub const anon12891_AudioDevicePropertyVoiceActivityDetectionEnable: ObjectPropertySelector = 1983996971;
pub const anon12891_AudioDevicePropertyVoiceActivityDetectionState: ObjectPropertySelector = 1983997011;

extern "CoreAudio" fn AudioDeviceCreateIOProcID(
    inDevice: ObjectID,
    inProc: DeviceIOProc,
    inClientData: ?*anyopaque,
    outIOProcID: ?*DeviceIOProcID,
) callconv(.C) objc.OSStatus;
pub const deviceCreateIOProcID = AudioDeviceCreateIOProcID;

extern "CoreAudio" fn AudioDeviceCreateIOProcIDWithBlock(
    outIOProcID: ?*DeviceIOProcID,
    inDevice: ObjectID,
    inDispatchQueue: objc.dispatch_queue_t,
    inIOBlock: DeviceIOBlock,
) callconv(.C) objc.OSStatus;
pub const deviceCreateIOProcIDWithBlock = AudioDeviceCreateIOProcIDWithBlock;

extern "CoreAudio" fn AudioDeviceDestroyIOProcID(inDevice: ObjectID, inIOProcID: DeviceIOProcID) callconv(.C) objc.OSStatus;
pub const deviceDestroyIOProcID = AudioDeviceDestroyIOProcID;

extern "CoreAudio" fn AudioDeviceStart(inDevice: ObjectID, inProcID: DeviceIOProcID) callconv(.C) objc.OSStatus;
pub const deviceStart = AudioDeviceStart;

extern "CoreAudio" fn AudioDeviceStartAtTime(
    inDevice: ObjectID,
    inProcID: DeviceIOProcID,
    ioRequestedStartTime: ?*core_audio_types.TimeStamp,
    inFlags: objc.UInt32,
) callconv(.C) objc.OSStatus;
pub const deviceStartAtTime = AudioDeviceStartAtTime;

extern "CoreAudio" fn AudioDeviceStop(inDevice: ObjectID, inProcID: DeviceIOProcID) callconv(.C) objc.OSStatus;
pub const deviceStop = AudioDeviceStop;

extern "CoreAudio" fn AudioDeviceGetCurrentTime(inDevice: ObjectID, outTime: ?*core_audio_types.TimeStamp) callconv(.C) objc.OSStatus;
pub const deviceGetCurrentTime = AudioDeviceGetCurrentTime;

extern "CoreAudio" fn AudioDeviceTranslateTime(inDevice: ObjectID, inTime: ?*const core_audio_types.TimeStamp, outTime: ?*core_audio_types.TimeStamp) callconv(.C) objc.OSStatus;
pub const deviceTranslateTime = AudioDeviceTranslateTime;

extern "CoreAudio" fn AudioDeviceGetNearestStartTime(inDevice: ObjectID, ioRequestedStartTime: ?*core_audio_types.TimeStamp, inFlags: objc.UInt32) callconv(.C) objc.OSStatus;
pub const deviceGetNearestStartTime = AudioDeviceGetNearestStartTime;

pub const anon15461 = ClassID;
pub const anon15461_AudioAggregateDeviceClassID: ClassID = 1633773415;

pub const anon16781 = ObjectPropertySelector;
pub const anon16781_AudioAggregateDevicePropertyFullSubDeviceList: ObjectPropertySelector = 1735554416;
pub const anon16781_AudioAggregateDevicePropertyActiveSubDeviceList: ObjectPropertySelector = 1634169456;
pub const anon16781_AudioAggregateDevicePropertyComposition: ObjectPropertySelector = 1633906541;
pub const anon16781_AudioAggregateDevicePropertyMainSubDevice: ObjectPropertySelector = 1634562932;
pub const anon16781_AudioAggregateDevicePropertyClockDevice: ObjectPropertySelector = 1634755428;
pub const anon16781_AudioAggregateDevicePropertyTapList: ObjectPropertySelector = 1952542755;
pub const anon16781_AudioAggregateDevicePropertySubTapList: ObjectPropertySelector = 1635017072;

pub const anon17001 = objc.UInt32;
pub const anon17001_AudioAggregateDriftCompensationMinQuality: objc.UInt32 = 0;
pub const anon17001_AudioAggregateDriftCompensationLowQuality: objc.UInt32 = 32;
pub const anon17001_AudioAggregateDriftCompensationMediumQuality: objc.UInt32 = 64;
pub const anon17001_AudioAggregateDriftCompensationHighQuality: objc.UInt32 = 96;
pub const anon17001_AudioAggregateDriftCompensationMaxQuality: objc.UInt32 = 127;

pub const anon17191 = ClassID;
pub const anon17191_AudioSubDeviceClassID: ClassID = 1634956642;

pub const anon17321 = objc.UInt32;
pub const anon17321_AudioSubDeviceDriftCompensationMinQuality: objc.UInt32 = 0;
pub const anon17321_AudioSubDeviceDriftCompensationLowQuality: objc.UInt32 = 32;
pub const anon17321_AudioSubDeviceDriftCompensationMediumQuality: objc.UInt32 = 64;
pub const anon17321_AudioSubDeviceDriftCompensationHighQuality: objc.UInt32 = 96;
pub const anon17321_AudioSubDeviceDriftCompensationMaxQuality: objc.UInt32 = 127;

pub const anon18291 = ObjectPropertySelector;
pub const anon18291_AudioSubDevicePropertyExtraLatency: ObjectPropertySelector = 2020373603;
pub const anon18291_AudioSubDevicePropertyDriftCompensation: ObjectPropertySelector = 1685218932;
pub const anon18291_AudioSubDevicePropertyDriftCompensationQuality: ObjectPropertySelector = 1685218929;

pub const anon18461 = ClassID;
pub const anon18461_AudioSubTapClassID: ClassID = 1937006960;

pub const anon19151 = ObjectPropertySelector;
pub const anon19151_AudioSubTapPropertyExtraLatency: ObjectPropertySelector = 2020373603;
pub const anon19151_AudioSubTapPropertyDriftCompensation: ObjectPropertySelector = 1685218932;
pub const anon19151_AudioSubTapPropertyDriftCompensationQuality: ObjectPropertySelector = 1685218929;

pub const anon19331 = ClassID;
pub const anon19331_AudioProcessClassID: ClassID = 1668050548;

pub const anon19711 = ObjectPropertySelector;
pub const anon19711_AudioProcessPropertyPID: ObjectPropertySelector = 1886415204;
pub const anon19711_AudioProcessPropertyBundleID: ObjectPropertySelector = 1885497700;
pub const anon19711_AudioProcessPropertyDevices: ObjectPropertySelector = 1885632035;
pub const anon19711_AudioProcessPropertyIsRunning: ObjectPropertySelector = 1885958719;
pub const anon19711_AudioProcessPropertyIsRunningInput: ObjectPropertySelector = 1885958761;
pub const anon19711_AudioProcessPropertyIsRunningOutput: ObjectPropertySelector = 1885958767;

pub const anon19931 = ClassID;
pub const anon19931_AudioTapClassID: ClassID = 1952672883;

pub const anon20181 = ObjectPropertySelector;
pub const anon20181_AudioTapPropertyUID: ObjectPropertySelector = 1953851748;
pub const anon20181_AudioTapPropertyDescription: ObjectPropertySelector = 1952740195;
pub const anon20181_AudioTapPropertyFormat: ObjectPropertySelector = 1952869748;

pub const anon481 = ObjectPropertyScope;
pub const anon481_AudioDevicePropertyScopeInput: ObjectPropertyScope = 1768845428;
pub const anon481_AudioDevicePropertyScopeOutput: ObjectPropertyScope = 1869968496;
pub const anon481_AudioDevicePropertyScopePlayThrough: ObjectPropertyScope = 1886679669;

pub const anon691 = ObjectPropertySelector;
pub const anon691_AudioPropertyWildcardPropertyID: ObjectPropertySelector = 707406378;

pub const anon791 = ObjectPropertyElement;
pub const anon791_AudioPropertyWildcardChannel: ObjectPropertyElement = -1;

pub const anon961 = ClassID;
pub const anon961_AudioISubOwnerControlClassID: ClassID = 1635017576;

pub const anon1131 = ObjectPropertySelector;
pub const anon1131_AudioLevelControlPropertyDecibelsToScalarTransferFunction: ObjectPropertySelector = 1818457190;

pub const LevelControlTransferFunction = objc.UInt32;
pub const LevelControlTransferFunction_TranferFunctionLinear: objc.UInt32 = 0;
pub const LevelControlTransferFunction_TranferFunction1Over3: objc.UInt32 = 1;
pub const LevelControlTransferFunction_TranferFunction1Over2: objc.UInt32 = 2;
pub const LevelControlTransferFunction_TranferFunction3Over4: objc.UInt32 = 3;
pub const LevelControlTransferFunction_TranferFunction3Over2: objc.UInt32 = 4;
pub const LevelControlTransferFunction_TranferFunction2Over1: objc.UInt32 = 5;
pub const LevelControlTransferFunction_TranferFunction3Over1: objc.UInt32 = 6;
pub const LevelControlTransferFunction_TranferFunction4Over1: objc.UInt32 = 7;
pub const LevelControlTransferFunction_TranferFunction5Over1: objc.UInt32 = 8;
pub const LevelControlTransferFunction_TranferFunction6Over1: objc.UInt32 = 9;
pub const LevelControlTransferFunction_TranferFunction7Over1: objc.UInt32 = 10;
pub const LevelControlTransferFunction_TranferFunction8Over1: objc.UInt32 = 11;
pub const LevelControlTransferFunction_TranferFunction9Over1: objc.UInt32 = 12;
pub const LevelControlTransferFunction_TranferFunction10Over1: objc.UInt32 = 13;
pub const LevelControlTransferFunction_TranferFunction11Over1: objc.UInt32 = 14;
pub const LevelControlTransferFunction_TranferFunction12Over1: objc.UInt32 = 15;

pub const HardwarePropertyID = ObjectPropertySelector;

pub const HardwarePropertyListenerProc = objc.OSStatus;

pub const anon2161 = ObjectPropertySelector;
pub const anon2161_AudioHardwarePropertyRunLoop: ObjectPropertySelector = 1919839344;
pub const anon2161_AudioHardwarePropertyDeviceForUID: ObjectPropertySelector = 1685416292;
pub const anon2161_AudioHardwarePropertyPlugInForBundleID: ObjectPropertySelector = 1885954665;
pub const anon2161_AudioHardwarePropertyProcessIsMaster: ObjectPropertySelector = 1835103092;

extern "CoreAudio" fn AudioHardwareAddRunLoopSource(inRunLoopSource: core_foundation.RunLoopSourceRef) callconv(.C) objc.OSStatus;
pub const hardwareAddRunLoopSource = AudioHardwareAddRunLoopSource;

extern "CoreAudio" fn AudioHardwareRemoveRunLoopSource(inRunLoopSource: core_foundation.RunLoopSourceRef) callconv(.C) objc.OSStatus;
pub const hardwareRemoveRunLoopSource = AudioHardwareRemoveRunLoopSource;

extern "CoreAudio" fn AudioHardwareGetPropertyInfo(inPropertyID: HardwarePropertyID, outSize: ?*objc.UInt32, outWritable: ?*objc.Boolean) callconv(.C) objc.OSStatus;
pub const hardwareGetPropertyInfo = AudioHardwareGetPropertyInfo;

extern "CoreAudio" fn AudioHardwareGetProperty(inPropertyID: HardwarePropertyID, ioPropertyDataSize: ?*objc.UInt32, outPropertyData: ?*anyopaque) callconv(.C) objc.OSStatus;
pub const hardwareGetProperty = AudioHardwareGetProperty;

extern "CoreAudio" fn AudioHardwareSetProperty(inPropertyID: HardwarePropertyID, inPropertyDataSize: objc.UInt32, inPropertyData: ?*const anyopaque) callconv(.C) objc.OSStatus;
pub const hardwareSetProperty = AudioHardwareSetProperty;

extern "CoreAudio" fn AudioHardwareAddPropertyListener(inPropertyID: HardwarePropertyID, inProc: HardwarePropertyListenerProc, inClientData: ?*anyopaque) callconv(.C) objc.OSStatus;
pub const hardwareAddPropertyListener = AudioHardwareAddPropertyListener;

extern "CoreAudio" fn AudioHardwareRemovePropertyListener(inPropertyID: HardwarePropertyID, inProc: HardwarePropertyListenerProc) callconv(.C) objc.OSStatus;
pub const hardwareRemovePropertyListener = AudioHardwareRemovePropertyListener;

pub const DeviceID = ObjectID;

pub const DevicePropertyID = ObjectPropertySelector;

pub const DevicePropertyListenerProc = objc.OSStatus;

pub const anon4571 = ObjectID;
pub const anon4571_AudioDeviceUnknown: ObjectID = 0;

pub const anon4691 = objc.UInt32;
pub const anon4691_AudioDeviceTransportTypeAutoAggregate: objc.UInt32 = 1718055536;

pub const anon5061 = ObjectPropertySelector;
pub const anon5061_AudioDevicePropertyVolumeDecibelsToScalarTransferFunction: ObjectPropertySelector = 1986229350;
pub const anon5061_AudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction: ObjectPropertySelector = 1836479590;
pub const anon5061_AudioDevicePropertyDriverShouldOwniSub: ObjectPropertySelector = 1769174370;
pub const anon5061_AudioDevicePropertySubVolumeDecibelsToScalarTransferFunction: ObjectPropertySelector = 1937142886;

pub const anon6711 = ObjectPropertySelector;
pub const anon6711_AudioDevicePropertyDeviceName: ObjectPropertySelector = 1851878757;
pub const anon6711_AudioDevicePropertyDeviceNameCFString: ObjectPropertySelector = 1819173229;
pub const anon6711_AudioDevicePropertyDeviceManufacturer: ObjectPropertySelector = 1835101042;
pub const anon6711_AudioDevicePropertyDeviceManufacturerCFString: ObjectPropertySelector = 1819107691;
pub const anon6711_AudioDevicePropertyRegisterBufferList: ObjectPropertySelector = 1919055206;
pub const anon6711_AudioDevicePropertyBufferSize: ObjectPropertySelector = 1651730810;
pub const anon6711_AudioDevicePropertyBufferSizeRange: ObjectPropertySelector = 1651735075;
pub const anon6711_AudioDevicePropertyChannelName: ObjectPropertySelector = 1667788397;
pub const anon6711_AudioDevicePropertyChannelNameCFString: ObjectPropertySelector = 1818454126;
pub const anon6711_AudioDevicePropertyChannelCategoryName: ObjectPropertySelector = 1667460717;
pub const anon6711_AudioDevicePropertyChannelCategoryNameCFString: ObjectPropertySelector = 1818452846;
pub const anon6711_AudioDevicePropertyChannelNumberName: ObjectPropertySelector = 1668181613;
pub const anon6711_AudioDevicePropertyChannelNumberNameCFString: ObjectPropertySelector = 1818455662;
pub const anon6711_AudioDevicePropertySupportsMixing: ObjectPropertySelector = 1835628607;
pub const anon6711_AudioDevicePropertyStreamFormat: ObjectPropertySelector = 1936092532;
pub const anon6711_AudioDevicePropertyStreamFormats: ObjectPropertySelector = 1936092451;
pub const anon6711_AudioDevicePropertyStreamFormatSupported: ObjectPropertySelector = 1936092479;
pub const anon6711_AudioDevicePropertyStreamFormatMatch: ObjectPropertySelector = 1936092525;
pub const anon6711_AudioDevicePropertyDataSourceNameForID: ObjectPropertySelector = 1936941934;
pub const anon6711_AudioDevicePropertyClockSourceNameForID: ObjectPropertySelector = 1668506478;
pub const anon6711_AudioDevicePropertyPlayThruDestinationNameForID: ObjectPropertySelector = 1835295854;
pub const anon6711_AudioDevicePropertyChannelNominalLineLevelNameForID: ObjectPropertySelector = 1668181110;
pub const anon6711_AudioDevicePropertyHighPassFilterSettingNameForID: ObjectPropertySelector = 1667787120;

extern "CoreAudio" fn AudioDeviceAddIOProc(inDevice: DeviceID, inProc: DeviceIOProc, inClientData: ?*anyopaque) callconv(.C) objc.OSStatus;
pub const deviceAddIOProc = AudioDeviceAddIOProc;

extern "CoreAudio" fn AudioDeviceRemoveIOProc(inDevice: DeviceID, inProc: DeviceIOProc) callconv(.C) objc.OSStatus;
pub const deviceRemoveIOProc = AudioDeviceRemoveIOProc;

extern "CoreAudio" fn AudioDeviceRead(inDevice: DeviceID, inStartTime: ?*const core_audio_types.TimeStamp, outData: ?*core_audio_types.BufferList) callconv(.C) objc.OSStatus;
pub const deviceRead = AudioDeviceRead;

extern "CoreAudio" fn AudioDeviceGetPropertyInfo(
    inDevice: DeviceID,
    inChannel: objc.UInt32,
    isInput: objc.Boolean,
    inPropertyID: DevicePropertyID,
    outSize: ?*objc.UInt32,
    outWritable: ?*objc.Boolean,
) callconv(.C) objc.OSStatus;
pub const deviceGetPropertyInfo = AudioDeviceGetPropertyInfo;

extern "CoreAudio" fn AudioDeviceGetProperty(
    inDevice: DeviceID,
    inChannel: objc.UInt32,
    isInput: objc.Boolean,
    inPropertyID: DevicePropertyID,
    ioPropertyDataSize: ?*objc.UInt32,
    outPropertyData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const deviceGetProperty = AudioDeviceGetProperty;

extern "CoreAudio" fn AudioDeviceSetProperty(
    inDevice: DeviceID,
    inWhen: ?*const core_audio_types.TimeStamp,
    inChannel: objc.UInt32,
    isInput: objc.Boolean,
    inPropertyID: DevicePropertyID,
    inPropertyDataSize: objc.UInt32,
    inPropertyData: ?*const anyopaque,
) callconv(.C) objc.OSStatus;
pub const deviceSetProperty = AudioDeviceSetProperty;

extern "CoreAudio" fn AudioDeviceAddPropertyListener(
    inDevice: DeviceID,
    inChannel: objc.UInt32,
    isInput: objc.Boolean,
    inPropertyID: DevicePropertyID,
    inProc: DevicePropertyListenerProc,
    inClientData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const deviceAddPropertyListener = AudioDeviceAddPropertyListener;

extern "CoreAudio" fn AudioDeviceRemovePropertyListener(
    inDevice: DeviceID,
    inChannel: objc.UInt32,
    isInput: objc.Boolean,
    inPropertyID: DevicePropertyID,
    inProc: DevicePropertyListenerProc,
) callconv(.C) objc.OSStatus;
pub const deviceRemovePropertyListener = AudioDeviceRemovePropertyListener;

pub const StreamID = ObjectID;

pub const StreamPropertyListenerProc = objc.OSStatus;

pub const anon9851 = ObjectID;
pub const anon9851_AudioStreamUnknown: ObjectID = 0;

pub const anon10321 = ObjectPropertySelector;
pub const anon10321_AudioStreamPropertyOwningDevice: ObjectPropertySelector = 1937007734;
pub const anon10321_AudioStreamPropertyPhysicalFormats: ObjectPropertySelector = 1885762595;
pub const anon10321_AudioStreamPropertyPhysicalFormatSupported: ObjectPropertySelector = 1885762623;
pub const anon10321_AudioStreamPropertyPhysicalFormatMatch: ObjectPropertySelector = 1885762669;

extern "CoreAudio" fn AudioStreamGetPropertyInfo(
    inStream: StreamID,
    inChannel: objc.UInt32,
    inPropertyID: DevicePropertyID,
    outSize: ?*objc.UInt32,
    outWritable: ?*objc.Boolean,
) callconv(.C) objc.OSStatus;
pub const streamGetPropertyInfo = AudioStreamGetPropertyInfo;

extern "CoreAudio" fn AudioStreamGetProperty(
    inStream: StreamID,
    inChannel: objc.UInt32,
    inPropertyID: DevicePropertyID,
    ioPropertyDataSize: ?*objc.UInt32,
    outPropertyData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const streamGetProperty = AudioStreamGetProperty;

extern "CoreAudio" fn AudioStreamSetProperty(
    inStream: StreamID,
    inWhen: ?*const core_audio_types.TimeStamp,
    inChannel: objc.UInt32,
    inPropertyID: DevicePropertyID,
    inPropertyDataSize: objc.UInt32,
    inPropertyData: ?*const anyopaque,
) callconv(.C) objc.OSStatus;
pub const streamSetProperty = AudioStreamSetProperty;

extern "CoreAudio" fn AudioStreamAddPropertyListener(
    inStream: StreamID,
    inChannel: objc.UInt32,
    inPropertyID: DevicePropertyID,
    inProc: StreamPropertyListenerProc,
    inClientData: ?*anyopaque,
) callconv(.C) objc.OSStatus;
pub const streamAddPropertyListener = AudioStreamAddPropertyListener;

extern "CoreAudio" fn AudioStreamRemovePropertyListener(
    inStream: StreamID,
    inChannel: objc.UInt32,
    inPropertyID: DevicePropertyID,
    inProc: StreamPropertyListenerProc,
) callconv(.C) objc.OSStatus;
pub const streamRemovePropertyListener = AudioStreamRemovePropertyListener;

pub const anon11891 = ClassID;
pub const anon11891_AudioBootChimeVolumeControlClassID: ClassID = 1886544237;

pub const anon12091 = ObjectPropertySelector;
pub const anon12091_AudioControlPropertyVariant: ObjectPropertySelector = 1668702578;

pub const anon12231 = ObjectPropertySelector;
pub const anon12231_AudioClockSourceControlPropertyItemKind: ObjectPropertySelector = 1668049771;

extern "CoreAudio" fn AudioGetCurrentHostTime() callconv(.C) objc.UInt64;
pub const getCurrentHostTime = AudioGetCurrentHostTime;

extern "CoreAudio" fn AudioGetHostClockFrequency() callconv(.C) objc.Float64;
pub const getHostClockFrequency = AudioGetHostClockFrequency;

extern "CoreAudio" fn AudioGetHostClockMinimumTimeDelta() callconv(.C) objc.UInt32;
pub const getHostClockMinimumTimeDelta = AudioGetHostClockMinimumTimeDelta;

extern "CoreAudio" fn AudioConvertHostTimeToNanos(inHostTime: objc.UInt64) callconv(.C) objc.UInt64;
pub const convertHostTimeToNanos = AudioConvertHostTimeToNanos;

extern "CoreAudio" fn AudioConvertNanosToHostTime(inNanos: objc.UInt64) callconv(.C) objc.UInt64;
pub const convertNanosToHostTime = AudioConvertNanosToHostTime;
