// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL NOT BE MAINTAINED.

const std = @import("std");
const objc = @import("objc.zig"); // Objective-C Runtime in zig.

pub const anon731 = objc.OSStatus;
pub const anon731_Audio_NoError: objc.OSStatus = 0;
pub const anon731_Audio_UnimplementedError: objc.OSStatus = -4;
pub const anon731_Audio_FileNotFoundError: objc.OSStatus = -43;
pub const anon731_Audio_FilePermissionError: objc.OSStatus = -54;
pub const anon731_Audio_TooManyFilesOpenError: objc.OSStatus = -42;
pub const anon731_Audio_BadFilePathError: objc.OSStatus = 561017960;
pub const anon731_Audio_ParamError: objc.OSStatus = -50;
pub const anon731_Audio_MemFullError: objc.OSStatus = -108;

pub const ValueRange = extern struct {
    mMinimum: objc.Float64,
    mMaximum: objc.Float64,
};

pub const ValueTranslation = extern struct {
    mInputData: ?*anyopaque,
    mInputDataSize: objc.UInt32,
    mOutputData: ?*anyopaque,
    mOutputDataSize: objc.UInt32,
};

pub const Buffer = extern struct {
    mNumberChannels: objc.UInt32,
    mDataByteSize: objc.UInt32,
    mData: ?*anyopaque,
};

pub const BufferList = extern struct {
    mNumberBuffers: objc.UInt32,
    mBuffers: Buffer,
};

pub const SampleType = objc.Float32;

pub const UnitSampleType = objc.Float32;

pub const FormatID = objc.UInt32;

pub const FormatFlags = objc.UInt32;

pub const StreamBasicDescription = extern struct {
    mSampleRate: objc.Float64,
    mFormatID: FormatID,
    mFormatFlags: FormatFlags,
    mBytesPerPacket: objc.UInt32,
    mFramesPerPacket: objc.UInt32,
    mBytesPerFrame: objc.UInt32,
    mChannelsPerFrame: objc.UInt32,
    mBitsPerChannel: objc.UInt32,
    mReserved: objc.UInt32,
};

pub const anon3721 = FormatID;
pub const anon3721_AudioFormatLinearPCM: FormatID = 1819304813;
pub const anon3721_AudioFormatAC3: FormatID = 1633889587;
pub const anon3721_AudioFormat60958AC3: FormatID = 1667326771;
pub const anon3721_AudioFormatAppleIMA4: FormatID = 1768775988;
pub const anon3721_AudioFormatMPEG4AAC: FormatID = 1633772320;
pub const anon3721_AudioFormatMPEG4CELP: FormatID = 1667591280;
pub const anon3721_AudioFormatMPEG4HVXC: FormatID = 1752594531;
pub const anon3721_AudioFormatMPEG4TwinVQ: FormatID = 1953986161;
pub const anon3721_AudioFormatMACE3: FormatID = 1296122675;
pub const anon3721_AudioFormatMACE6: FormatID = 1296122678;
pub const anon3721_AudioFormatULaw: FormatID = 1970037111;
pub const anon3721_AudioFormatALaw: FormatID = 1634492791;
pub const anon3721_AudioFormatQDesign: FormatID = 1363430723;
pub const anon3721_AudioFormatQDesign2: FormatID = 1363430706;
pub const anon3721_AudioFormatQUALCOMM: FormatID = 1365470320;
pub const anon3721_AudioFormatMPEGLayer1: FormatID = 778924081;
pub const anon3721_AudioFormatMPEGLayer2: FormatID = 778924082;
pub const anon3721_AudioFormatMPEGLayer3: FormatID = 778924083;
pub const anon3721_AudioFormatTimeCode: FormatID = 1953066341;
pub const anon3721_AudioFormatMIDIStream: FormatID = 1835623529;
pub const anon3721_AudioFormatParameterValueStream: FormatID = 1634760307;
pub const anon3721_AudioFormatAppleLossless: FormatID = 1634492771;
pub const anon3721_AudioFormatMPEG4AAC_HE: FormatID = 1633772392;
pub const anon3721_AudioFormatMPEG4AAC_LD: FormatID = 1633772396;
pub const anon3721_AudioFormatMPEG4AAC_ELD: FormatID = 1633772389;
pub const anon3721_AudioFormatMPEG4AAC_ELD_SBR: FormatID = 1633772390;
pub const anon3721_AudioFormatMPEG4AAC_ELD_V2: FormatID = 1633772391;
pub const anon3721_AudioFormatMPEG4AAC_HE_V2: FormatID = 1633772400;
pub const anon3721_AudioFormatMPEG4AAC_Spatial: FormatID = 1633772403;
pub const anon3721_AudioFormatMPEGD_USAC: FormatID = 1970495843;
pub const anon3721_AudioFormatAMR: FormatID = 1935764850;
pub const anon3721_AudioFormatAMR_WB: FormatID = 1935767394;
pub const anon3721_AudioFormatAudible: FormatID = 1096107074;
pub const anon3721_AudioFormatiLBC: FormatID = 1768710755;
pub const anon3721_AudioFormatDVIIntelIMA: FormatID = 1836253201;
pub const anon3721_AudioFormatMicrosoftGSM: FormatID = 1836253233;
pub const anon3721_AudioFormatAES3: FormatID = 1634038579;
pub const anon3721_AudioFormatEnhancedAC3: FormatID = 1700998451;
pub const anon3721_AudioFormatFLAC: FormatID = 1718378851;
pub const anon3721_AudioFormatOpus: FormatID = 1869641075;
pub const anon3721_AudioFormatAPAC: FormatID = 1634754915;

pub const anon5031 = FormatFlags;
pub const anon5031_AudioFormatFlagIsFloat: FormatFlags = 1;
pub const anon5031_AudioFormatFlagIsBigEndian: FormatFlags = 2;
pub const anon5031_AudioFormatFlagIsSignedInteger: FormatFlags = 4;
pub const anon5031_AudioFormatFlagIsPacked: FormatFlags = 8;
pub const anon5031_AudioFormatFlagIsAlignedHigh: FormatFlags = 16;
pub const anon5031_AudioFormatFlagIsNonInterleaved: FormatFlags = 32;
pub const anon5031_AudioFormatFlagIsNonMixable: FormatFlags = 64;
pub const anon5031_AudioFormatFlagsAreAllClear: FormatFlags = -2147483648;
pub const anon5031_LinearPCMFormatFlagIsFloat: FormatFlags = 1;
pub const anon5031_LinearPCMFormatFlagIsBigEndian: FormatFlags = 2;
pub const anon5031_LinearPCMFormatFlagIsSignedInteger: FormatFlags = 4;
pub const anon5031_LinearPCMFormatFlagIsPacked: FormatFlags = 8;
pub const anon5031_LinearPCMFormatFlagIsAlignedHigh: FormatFlags = 16;
pub const anon5031_LinearPCMFormatFlagIsNonInterleaved: FormatFlags = 32;
pub const anon5031_LinearPCMFormatFlagIsNonMixable: FormatFlags = 64;
pub const anon5031_LinearPCMFormatFlagsSampleFractionShift: FormatFlags = 7;
pub const anon5031_LinearPCMFormatFlagsSampleFractionMask: FormatFlags = 8064;
pub const anon5031_LinearPCMFormatFlagsAreAllClear: FormatFlags = -2147483648;
pub const anon5031_AppleLosslessFormatFlag_16BitSourceData: FormatFlags = 1;
pub const anon5031_AppleLosslessFormatFlag_20BitSourceData: FormatFlags = 2;
pub const anon5031_AppleLosslessFormatFlag_24BitSourceData: FormatFlags = 3;
pub const anon5031_AppleLosslessFormatFlag_32BitSourceData: FormatFlags = 4;

pub const anon5541 = FormatFlags;
pub const anon5541_AudioFormatFlagsNativeEndian: FormatFlags = 0;
pub const anon5541_AudioFormatFlagsCanonical: FormatFlags = 9;
pub const anon5541_AudioFormatFlagsAudioUnitCanonical: FormatFlags = 41;
pub const anon5541_AudioFormatFlagsNativeFloatPacked: FormatFlags = 9;

pub const StreamPacketDescription = extern struct {
    mStartOffset: objc.SInt64,
    mVariableFramesInPacket: objc.UInt32,
    mDataByteSize: objc.UInt32,
};

pub const SMPTETimeType = objc.UInt32;
pub const SMPTETimeType_24: objc.UInt32 = 0;
pub const SMPTETimeType_25: objc.UInt32 = 1;
pub const SMPTETimeType_30Drop: objc.UInt32 = 2;
pub const SMPTETimeType_30: objc.UInt32 = 3;
pub const SMPTETimeType_2997: objc.UInt32 = 4;
pub const SMPTETimeType_2997Drop: objc.UInt32 = 5;
pub const SMPTETimeType_60: objc.UInt32 = 6;
pub const SMPTETimeType_5994: objc.UInt32 = 7;
pub const SMPTETimeType_60Drop: objc.UInt32 = 8;
pub const SMPTETimeType_5994Drop: objc.UInt32 = 9;
pub const SMPTETimeType_50: objc.UInt32 = 10;
pub const SMPTETimeType_2398: objc.UInt32 = 11;

pub const SMPTETimeFlags = objc.UInt32;
pub const SMPTETimeFlags_Unknown: objc.UInt32 = 0;
pub const SMPTETimeFlags_Valid: objc.UInt32 = 1;
pub const SMPTETimeFlags_Running: objc.UInt32 = 2;

pub const SMPTETime = extern struct {
    mSubframes: objc.SInt16,
    mSubframeDivisor: objc.SInt16,
    mCounter: objc.UInt32,
    mType: SMPTETimeType,
    mFlags: SMPTETimeFlags,
    mHours: objc.SInt16,
    mMinutes: objc.SInt16,
    mSeconds: objc.SInt16,
    mFrames: objc.SInt16,
};

pub const TimeStampFlags = objc.UInt32;
pub const TimeStampFlags_NothingValid: objc.UInt32 = 0;
pub const TimeStampFlags_SampleTimeValid: objc.UInt32 = 1;
pub const TimeStampFlags_HostTimeValid: objc.UInt32 = 2;
pub const TimeStampFlags_RateScalarValid: objc.UInt32 = 4;
pub const TimeStampFlags_WordClockTimeValid: objc.UInt32 = 8;
pub const TimeStampFlags_SMPTETimeValid: objc.UInt32 = 16;
pub const TimeStampFlags_SampleHostTimeValid: objc.UInt32 = 3;

pub const TimeStamp = extern struct {
    mSampleTime: objc.Float64,
    mHostTime: objc.UInt64,
    mRateScalar: objc.Float64,
    mWordClockTime: objc.UInt64,
    mSMPTETime: SMPTETime,
    mFlags: TimeStampFlags,
    mReserved: objc.UInt32,
};

pub const ClassDescription = extern struct {
    mType: objc.OSType,
    mSubType: objc.OSType,
    mManufacturer: objc.OSType,
};

pub const ChannelLabel = objc.UInt32;

pub const ChannelLayoutTag = objc.UInt32;

pub const anon9121 = ChannelLabel;
pub const anon9121_AudioChannelLabel_Unknown: ChannelLabel = -1;
pub const anon9121_AudioChannelLabel_Unused: ChannelLabel = 0;
pub const anon9121_AudioChannelLabel_UseCoordinates: ChannelLabel = 100;
pub const anon9121_AudioChannelLabel_Left: ChannelLabel = 1;
pub const anon9121_AudioChannelLabel_Right: ChannelLabel = 2;
pub const anon9121_AudioChannelLabel_Center: ChannelLabel = 3;
pub const anon9121_AudioChannelLabel_LFEScreen: ChannelLabel = 4;
pub const anon9121_AudioChannelLabel_LeftSurround: ChannelLabel = 5;
pub const anon9121_AudioChannelLabel_RightSurround: ChannelLabel = 6;
pub const anon9121_AudioChannelLabel_LeftCenter: ChannelLabel = 7;
pub const anon9121_AudioChannelLabel_RightCenter: ChannelLabel = 8;
pub const anon9121_AudioChannelLabel_CenterSurround: ChannelLabel = 9;
pub const anon9121_AudioChannelLabel_LeftSurroundDirect: ChannelLabel = 10;
pub const anon9121_AudioChannelLabel_RightSurroundDirect: ChannelLabel = 11;
pub const anon9121_AudioChannelLabel_TopCenterSurround: ChannelLabel = 12;
pub const anon9121_AudioChannelLabel_VerticalHeightLeft: ChannelLabel = 13;
pub const anon9121_AudioChannelLabel_VerticalHeightCenter: ChannelLabel = 14;
pub const anon9121_AudioChannelLabel_VerticalHeightRight: ChannelLabel = 15;
pub const anon9121_AudioChannelLabel_TopBackLeft: ChannelLabel = 16;
pub const anon9121_AudioChannelLabel_TopBackCenter: ChannelLabel = 17;
pub const anon9121_AudioChannelLabel_TopBackRight: ChannelLabel = 18;
pub const anon9121_AudioChannelLabel_RearSurroundLeft: ChannelLabel = 33;
pub const anon9121_AudioChannelLabel_RearSurroundRight: ChannelLabel = 34;
pub const anon9121_AudioChannelLabel_LeftWide: ChannelLabel = 35;
pub const anon9121_AudioChannelLabel_RightWide: ChannelLabel = 36;
pub const anon9121_AudioChannelLabel_LFE2: ChannelLabel = 37;
pub const anon9121_AudioChannelLabel_LeftTotal: ChannelLabel = 38;
pub const anon9121_AudioChannelLabel_RightTotal: ChannelLabel = 39;
pub const anon9121_AudioChannelLabel_HearingImpaired: ChannelLabel = 40;
pub const anon9121_AudioChannelLabel_Narration: ChannelLabel = 41;
pub const anon9121_AudioChannelLabel_Mono: ChannelLabel = 42;
pub const anon9121_AudioChannelLabel_DialogCentricMix: ChannelLabel = 43;
pub const anon9121_AudioChannelLabel_CenterSurroundDirect: ChannelLabel = 44;
pub const anon9121_AudioChannelLabel_Haptic: ChannelLabel = 45;
pub const anon9121_AudioChannelLabel_LeftTopFront: ChannelLabel = 13;
pub const anon9121_AudioChannelLabel_CenterTopFront: ChannelLabel = 14;
pub const anon9121_AudioChannelLabel_RightTopFront: ChannelLabel = 15;
pub const anon9121_AudioChannelLabel_LeftTopMiddle: ChannelLabel = 49;
pub const anon9121_AudioChannelLabel_CenterTopMiddle: ChannelLabel = 12;
pub const anon9121_AudioChannelLabel_RightTopMiddle: ChannelLabel = 51;
pub const anon9121_AudioChannelLabel_LeftTopRear: ChannelLabel = 52;
pub const anon9121_AudioChannelLabel_CenterTopRear: ChannelLabel = 53;
pub const anon9121_AudioChannelLabel_RightTopRear: ChannelLabel = 54;
pub const anon9121_AudioChannelLabel_LeftSideSurround: ChannelLabel = 55;
pub const anon9121_AudioChannelLabel_RightSideSurround: ChannelLabel = 56;
pub const anon9121_AudioChannelLabel_LeftBottom: ChannelLabel = 57;
pub const anon9121_AudioChannelLabel_RightBottom: ChannelLabel = 58;
pub const anon9121_AudioChannelLabel_CenterBottom: ChannelLabel = 59;
pub const anon9121_AudioChannelLabel_LeftTopSurround: ChannelLabel = 60;
pub const anon9121_AudioChannelLabel_RightTopSurround: ChannelLabel = 61;
pub const anon9121_AudioChannelLabel_LFE3: ChannelLabel = 62;
pub const anon9121_AudioChannelLabel_LeftBackSurround: ChannelLabel = 63;
pub const anon9121_AudioChannelLabel_RightBackSurround: ChannelLabel = 64;
pub const anon9121_AudioChannelLabel_LeftEdgeOfScreen: ChannelLabel = 65;
pub const anon9121_AudioChannelLabel_RightEdgeOfScreen: ChannelLabel = 66;
pub const anon9121_AudioChannelLabel_Ambisonic_W: ChannelLabel = 200;
pub const anon9121_AudioChannelLabel_Ambisonic_X: ChannelLabel = 201;
pub const anon9121_AudioChannelLabel_Ambisonic_Y: ChannelLabel = 202;
pub const anon9121_AudioChannelLabel_Ambisonic_Z: ChannelLabel = 203;
pub const anon9121_AudioChannelLabel_MS_Mid: ChannelLabel = 204;
pub const anon9121_AudioChannelLabel_MS_Side: ChannelLabel = 205;
pub const anon9121_AudioChannelLabel_XY_X: ChannelLabel = 206;
pub const anon9121_AudioChannelLabel_XY_Y: ChannelLabel = 207;
pub const anon9121_AudioChannelLabel_BinauralLeft: ChannelLabel = 208;
pub const anon9121_AudioChannelLabel_BinauralRight: ChannelLabel = 209;
pub const anon9121_AudioChannelLabel_HeadphonesLeft: ChannelLabel = 301;
pub const anon9121_AudioChannelLabel_HeadphonesRight: ChannelLabel = 302;
pub const anon9121_AudioChannelLabel_ClickTrack: ChannelLabel = 304;
pub const anon9121_AudioChannelLabel_ForeignLanguage: ChannelLabel = 305;
pub const anon9121_AudioChannelLabel_Discrete: ChannelLabel = 400;
pub const anon9121_AudioChannelLabel_Discrete_0: ChannelLabel = 65536;
pub const anon9121_AudioChannelLabel_Discrete_1: ChannelLabel = 65537;
pub const anon9121_AudioChannelLabel_Discrete_2: ChannelLabel = 65538;
pub const anon9121_AudioChannelLabel_Discrete_3: ChannelLabel = 65539;
pub const anon9121_AudioChannelLabel_Discrete_4: ChannelLabel = 65540;
pub const anon9121_AudioChannelLabel_Discrete_5: ChannelLabel = 65541;
pub const anon9121_AudioChannelLabel_Discrete_6: ChannelLabel = 65542;
pub const anon9121_AudioChannelLabel_Discrete_7: ChannelLabel = 65543;
pub const anon9121_AudioChannelLabel_Discrete_8: ChannelLabel = 65544;
pub const anon9121_AudioChannelLabel_Discrete_9: ChannelLabel = 65545;
pub const anon9121_AudioChannelLabel_Discrete_10: ChannelLabel = 65546;
pub const anon9121_AudioChannelLabel_Discrete_11: ChannelLabel = 65547;
pub const anon9121_AudioChannelLabel_Discrete_12: ChannelLabel = 65548;
pub const anon9121_AudioChannelLabel_Discrete_13: ChannelLabel = 65549;
pub const anon9121_AudioChannelLabel_Discrete_14: ChannelLabel = 65550;
pub const anon9121_AudioChannelLabel_Discrete_15: ChannelLabel = 65551;
pub const anon9121_AudioChannelLabel_Discrete_65535: ChannelLabel = 131071;
pub const anon9121_AudioChannelLabel_HOA_ACN: ChannelLabel = 500;
pub const anon9121_AudioChannelLabel_HOA_ACN_0: ChannelLabel = 131072;
pub const anon9121_AudioChannelLabel_HOA_ACN_1: ChannelLabel = 131073;
pub const anon9121_AudioChannelLabel_HOA_ACN_2: ChannelLabel = 131074;
pub const anon9121_AudioChannelLabel_HOA_ACN_3: ChannelLabel = 131075;
pub const anon9121_AudioChannelLabel_HOA_ACN_4: ChannelLabel = 131076;
pub const anon9121_AudioChannelLabel_HOA_ACN_5: ChannelLabel = 131077;
pub const anon9121_AudioChannelLabel_HOA_ACN_6: ChannelLabel = 131078;
pub const anon9121_AudioChannelLabel_HOA_ACN_7: ChannelLabel = 131079;
pub const anon9121_AudioChannelLabel_HOA_ACN_8: ChannelLabel = 131080;
pub const anon9121_AudioChannelLabel_HOA_ACN_9: ChannelLabel = 131081;
pub const anon9121_AudioChannelLabel_HOA_ACN_10: ChannelLabel = 131082;
pub const anon9121_AudioChannelLabel_HOA_ACN_11: ChannelLabel = 131083;
pub const anon9121_AudioChannelLabel_HOA_ACN_12: ChannelLabel = 131084;
pub const anon9121_AudioChannelLabel_HOA_ACN_13: ChannelLabel = 131085;
pub const anon9121_AudioChannelLabel_HOA_ACN_14: ChannelLabel = 131086;
pub const anon9121_AudioChannelLabel_HOA_ACN_15: ChannelLabel = 131087;
pub const anon9121_AudioChannelLabel_HOA_ACN_65024: ChannelLabel = 196096;
pub const anon9121_AudioChannelLabel_HOA_SN3D: ChannelLabel = 131072;
pub const anon9121_AudioChannelLabel_HOA_N3D: ChannelLabel = 196608;
pub const anon9121_AudioChannelLabel_Object: ChannelLabel = 262144;
pub const anon9121_AudioChannelLabel_BeginReserved: ChannelLabel = -268435456;
pub const anon9121_AudioChannelLabel_EndReserved: ChannelLabel = -2;

pub const ChannelBitmap = objc.UInt32;
pub const ChannelBitmap_Bit_Left: objc.UInt32 = 1;
pub const ChannelBitmap_Bit_Right: objc.UInt32 = 2;
pub const ChannelBitmap_Bit_Center: objc.UInt32 = 4;
pub const ChannelBitmap_Bit_LFEScreen: objc.UInt32 = 8;
pub const ChannelBitmap_Bit_LeftSurround: objc.UInt32 = 16;
pub const ChannelBitmap_Bit_RightSurround: objc.UInt32 = 32;
pub const ChannelBitmap_Bit_LeftCenter: objc.UInt32 = 64;
pub const ChannelBitmap_Bit_RightCenter: objc.UInt32 = 128;
pub const ChannelBitmap_Bit_CenterSurround: objc.UInt32 = 256;
pub const ChannelBitmap_Bit_LeftSurroundDirect: objc.UInt32 = 512;
pub const ChannelBitmap_Bit_RightSurroundDirect: objc.UInt32 = 1024;
pub const ChannelBitmap_Bit_TopCenterSurround: objc.UInt32 = 2048;
pub const ChannelBitmap_Bit_VerticalHeightLeft: objc.UInt32 = 4096;
pub const ChannelBitmap_Bit_VerticalHeightCenter: objc.UInt32 = 8192;
pub const ChannelBitmap_Bit_VerticalHeightRight: objc.UInt32 = 16384;
pub const ChannelBitmap_Bit_TopBackLeft: objc.UInt32 = 32768;
pub const ChannelBitmap_Bit_TopBackCenter: objc.UInt32 = 65536;
pub const ChannelBitmap_Bit_TopBackRight: objc.UInt32 = 131072;
pub const ChannelBitmap_Bit_LeftTopFront: objc.UInt32 = 4096;
pub const ChannelBitmap_Bit_CenterTopFront: objc.UInt32 = 8192;
pub const ChannelBitmap_Bit_RightTopFront: objc.UInt32 = 16384;
pub const ChannelBitmap_Bit_LeftTopMiddle: objc.UInt32 = 2097152;
pub const ChannelBitmap_Bit_CenterTopMiddle: objc.UInt32 = 2048;
pub const ChannelBitmap_Bit_RightTopMiddle: objc.UInt32 = 8388608;
pub const ChannelBitmap_Bit_LeftTopRear: objc.UInt32 = 16777216;
pub const ChannelBitmap_Bit_CenterTopRear: objc.UInt32 = 33554432;
pub const ChannelBitmap_Bit_RightTopRear: objc.UInt32 = 67108864;

pub const ChannelFlags = objc.UInt32;
pub const ChannelFlags__AllOff: objc.UInt32 = 0;
pub const ChannelFlags__RectangularCoordinates: objc.UInt32 = 1;
pub const ChannelFlags__SphericalCoordinates: objc.UInt32 = 2;
pub const ChannelFlags__Meters: objc.UInt32 = 4;

pub const ChannelCoordinateIndex = objc.UInt32;
pub const ChannelCoordinateIndex_Coordinates_LeftRight: objc.UInt32 = 0;
pub const ChannelCoordinateIndex_Coordinates_BackFront: objc.UInt32 = 1;
pub const ChannelCoordinateIndex_Coordinates_DownUp: objc.UInt32 = 2;
pub const ChannelCoordinateIndex_Coordinates_Azimuth: objc.UInt32 = 0;
pub const ChannelCoordinateIndex_Coordinates_Elevation: objc.UInt32 = 1;
pub const ChannelCoordinateIndex_Coordinates_Distance: objc.UInt32 = 2;

pub const anon11541 = ChannelLayoutTag;
pub const anon11541_AudioChannelLayoutTag_UseChannelDescriptions: ChannelLayoutTag = 0;
pub const anon11541_AudioChannelLayoutTag_UseChannelBitmap: ChannelLayoutTag = 65536;
pub const anon11541_AudioChannelLayoutTag_Mono: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_Stereo: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_StereoHeadphones: ChannelLayoutTag = 6684674;
pub const anon11541_AudioChannelLayoutTag_MatrixStereo: ChannelLayoutTag = 6750210;
pub const anon11541_AudioChannelLayoutTag_MidSide: ChannelLayoutTag = 6815746;
pub const anon11541_AudioChannelLayoutTag_XY: ChannelLayoutTag = 6881282;
pub const anon11541_AudioChannelLayoutTag_Binaural: ChannelLayoutTag = 6946818;
pub const anon11541_AudioChannelLayoutTag_Ambisonic_B_Format: ChannelLayoutTag = 7012356;
pub const anon11541_AudioChannelLayoutTag_Quadraphonic: ChannelLayoutTag = 7077892;
pub const anon11541_AudioChannelLayoutTag_Pentagonal: ChannelLayoutTag = 7143429;
pub const anon11541_AudioChannelLayoutTag_Hexagonal: ChannelLayoutTag = 7208966;
pub const anon11541_AudioChannelLayoutTag_Octagonal: ChannelLayoutTag = 7274504;
pub const anon11541_AudioChannelLayoutTag_Cube: ChannelLayoutTag = 7340040;
pub const anon11541_AudioChannelLayoutTag_MPEG_1_0: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_MPEG_2_0: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_MPEG_3_0_A: ChannelLayoutTag = 7405571;
pub const anon11541_AudioChannelLayoutTag_MPEG_3_0_B: ChannelLayoutTag = 7471107;
pub const anon11541_AudioChannelLayoutTag_MPEG_4_0_A: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_MPEG_4_0_B: ChannelLayoutTag = 7602180;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_0_A: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_0_B: ChannelLayoutTag = 7733253;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_0_C: ChannelLayoutTag = 7798789;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_0_D: ChannelLayoutTag = 7864325;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_1_A: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_1_B: ChannelLayoutTag = 7995398;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_1_C: ChannelLayoutTag = 8060934;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_1_D: ChannelLayoutTag = 8126470;
pub const anon11541_AudioChannelLayoutTag_MPEG_6_1_A: ChannelLayoutTag = 8192007;
pub const anon11541_AudioChannelLayoutTag_MPEG_7_1_A: ChannelLayoutTag = 8257544;
pub const anon11541_AudioChannelLayoutTag_MPEG_7_1_B: ChannelLayoutTag = 8323080;
pub const anon11541_AudioChannelLayoutTag_MPEG_7_1_C: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_Emagic_Default_7_1: ChannelLayoutTag = 8454152;
pub const anon11541_AudioChannelLayoutTag_SMPTE_DTV: ChannelLayoutTag = 8519688;
pub const anon11541_AudioChannelLayoutTag_ITU_1_0: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_ITU_2_0: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_ITU_2_1: ChannelLayoutTag = 8585219;
pub const anon11541_AudioChannelLayoutTag_ITU_2_2: ChannelLayoutTag = 8650756;
pub const anon11541_AudioChannelLayoutTag_ITU_3_0: ChannelLayoutTag = 7405571;
pub const anon11541_AudioChannelLayoutTag_ITU_3_1: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_ITU_3_2: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_ITU_3_2_1: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_ITU_3_4_1: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_DVD_0: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_DVD_1: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_DVD_2: ChannelLayoutTag = 8585219;
pub const anon11541_AudioChannelLayoutTag_DVD_3: ChannelLayoutTag = 8650756;
pub const anon11541_AudioChannelLayoutTag_DVD_4: ChannelLayoutTag = 8716291;
pub const anon11541_AudioChannelLayoutTag_DVD_5: ChannelLayoutTag = 8781828;
pub const anon11541_AudioChannelLayoutTag_DVD_6: ChannelLayoutTag = 8847365;
pub const anon11541_AudioChannelLayoutTag_DVD_7: ChannelLayoutTag = 7405571;
pub const anon11541_AudioChannelLayoutTag_DVD_8: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_DVD_9: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_DVD_10: ChannelLayoutTag = 8912900;
pub const anon11541_AudioChannelLayoutTag_DVD_11: ChannelLayoutTag = 8978437;
pub const anon11541_AudioChannelLayoutTag_DVD_12: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_DVD_13: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_DVD_14: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_DVD_15: ChannelLayoutTag = 8912900;
pub const anon11541_AudioChannelLayoutTag_DVD_16: ChannelLayoutTag = 8978437;
pub const anon11541_AudioChannelLayoutTag_DVD_17: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_DVD_18: ChannelLayoutTag = 9043973;
pub const anon11541_AudioChannelLayoutTag_DVD_19: ChannelLayoutTag = 7733253;
pub const anon11541_AudioChannelLayoutTag_DVD_20: ChannelLayoutTag = 7995398;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_4: ChannelLayoutTag = 7077892;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_5: ChannelLayoutTag = 7143429;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_6: ChannelLayoutTag = 7208966;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_8: ChannelLayoutTag = 7274504;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_5_0: ChannelLayoutTag = 7733253;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_6_0: ChannelLayoutTag = 9109510;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_7_0: ChannelLayoutTag = 9175047;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_7_0_Front: ChannelLayoutTag = 9699335;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_5_1: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_6_1: ChannelLayoutTag = 8192007;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_7_1: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_AudioUnit_7_1_Front: ChannelLayoutTag = 8257544;
pub const anon11541_AudioChannelLayoutTag_AAC_3_0: ChannelLayoutTag = 7471107;
pub const anon11541_AudioChannelLayoutTag_AAC_Quadraphonic: ChannelLayoutTag = 7077892;
pub const anon11541_AudioChannelLayoutTag_AAC_4_0: ChannelLayoutTag = 7602180;
pub const anon11541_AudioChannelLayoutTag_AAC_5_0: ChannelLayoutTag = 7864325;
pub const anon11541_AudioChannelLayoutTag_AAC_5_1: ChannelLayoutTag = 8126470;
pub const anon11541_AudioChannelLayoutTag_AAC_6_0: ChannelLayoutTag = 9240582;
pub const anon11541_AudioChannelLayoutTag_AAC_6_1: ChannelLayoutTag = 9306119;
pub const anon11541_AudioChannelLayoutTag_AAC_7_0: ChannelLayoutTag = 9371655;
pub const anon11541_AudioChannelLayoutTag_AAC_7_1: ChannelLayoutTag = 8323080;
pub const anon11541_AudioChannelLayoutTag_AAC_7_1_B: ChannelLayoutTag = 11993096;
pub const anon11541_AudioChannelLayoutTag_AAC_7_1_C: ChannelLayoutTag = 12058632;
pub const anon11541_AudioChannelLayoutTag_AAC_Octagonal: ChannelLayoutTag = 9437192;
pub const anon11541_AudioChannelLayoutTag_TMH_10_2_std: ChannelLayoutTag = 9502736;
pub const anon11541_AudioChannelLayoutTag_TMH_10_2_full: ChannelLayoutTag = 9568277;
pub const anon11541_AudioChannelLayoutTag_AC3_1_0_1: ChannelLayoutTag = 9764866;
pub const anon11541_AudioChannelLayoutTag_AC3_3_0: ChannelLayoutTag = 9830403;
pub const anon11541_AudioChannelLayoutTag_AC3_3_1: ChannelLayoutTag = 9895940;
pub const anon11541_AudioChannelLayoutTag_AC3_3_0_1: ChannelLayoutTag = 9961476;
pub const anon11541_AudioChannelLayoutTag_AC3_2_1_1: ChannelLayoutTag = 10027012;
pub const anon11541_AudioChannelLayoutTag_AC3_3_1_1: ChannelLayoutTag = 10092549;
pub const anon11541_AudioChannelLayoutTag_EAC_6_0_A: ChannelLayoutTag = 10158086;
pub const anon11541_AudioChannelLayoutTag_EAC_7_0_A: ChannelLayoutTag = 10223623;
pub const anon11541_AudioChannelLayoutTag_EAC3_6_1_A: ChannelLayoutTag = 10289159;
pub const anon11541_AudioChannelLayoutTag_EAC3_6_1_B: ChannelLayoutTag = 10354695;
pub const anon11541_AudioChannelLayoutTag_EAC3_6_1_C: ChannelLayoutTag = 10420231;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_A: ChannelLayoutTag = 10485768;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_B: ChannelLayoutTag = 10551304;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_C: ChannelLayoutTag = 10616840;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_D: ChannelLayoutTag = 10682376;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_E: ChannelLayoutTag = 10747912;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_F: ChannelLayoutTag = 10813448;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_G: ChannelLayoutTag = 10878984;
pub const anon11541_AudioChannelLayoutTag_EAC3_7_1_H: ChannelLayoutTag = 10944520;
pub const anon11541_AudioChannelLayoutTag_DTS_3_1: ChannelLayoutTag = 11010052;
pub const anon11541_AudioChannelLayoutTag_DTS_4_1: ChannelLayoutTag = 11075589;
pub const anon11541_AudioChannelLayoutTag_DTS_6_0_A: ChannelLayoutTag = 11141126;
pub const anon11541_AudioChannelLayoutTag_DTS_6_0_B: ChannelLayoutTag = 11206662;
pub const anon11541_AudioChannelLayoutTag_DTS_6_0_C: ChannelLayoutTag = 11272198;
pub const anon11541_AudioChannelLayoutTag_DTS_6_1_A: ChannelLayoutTag = 11337735;
pub const anon11541_AudioChannelLayoutTag_DTS_6_1_B: ChannelLayoutTag = 11403271;
pub const anon11541_AudioChannelLayoutTag_DTS_6_1_C: ChannelLayoutTag = 11468807;
pub const anon11541_AudioChannelLayoutTag_DTS_7_0: ChannelLayoutTag = 11534343;
pub const anon11541_AudioChannelLayoutTag_DTS_7_1: ChannelLayoutTag = 11599880;
pub const anon11541_AudioChannelLayoutTag_DTS_8_0_A: ChannelLayoutTag = 11665416;
pub const anon11541_AudioChannelLayoutTag_DTS_8_0_B: ChannelLayoutTag = 11730952;
pub const anon11541_AudioChannelLayoutTag_DTS_8_1_A: ChannelLayoutTag = 11796489;
pub const anon11541_AudioChannelLayoutTag_DTS_8_1_B: ChannelLayoutTag = 11862025;
pub const anon11541_AudioChannelLayoutTag_DTS_6_1_D: ChannelLayoutTag = 11927559;
pub const anon11541_AudioChannelLayoutTag_WAVE_2_1: ChannelLayoutTag = 8716291;
pub const anon11541_AudioChannelLayoutTag_WAVE_3_0: ChannelLayoutTag = 7405571;
pub const anon11541_AudioChannelLayoutTag_WAVE_4_0_A: ChannelLayoutTag = 8650756;
pub const anon11541_AudioChannelLayoutTag_WAVE_4_0_B: ChannelLayoutTag = 12124164;
pub const anon11541_AudioChannelLayoutTag_WAVE_5_0_A: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_WAVE_5_0_B: ChannelLayoutTag = 12189701;
pub const anon11541_AudioChannelLayoutTag_WAVE_5_1_A: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_WAVE_5_1_B: ChannelLayoutTag = 12255238;
pub const anon11541_AudioChannelLayoutTag_WAVE_6_1: ChannelLayoutTag = 12320775;
pub const anon11541_AudioChannelLayoutTag_WAVE_7_1: ChannelLayoutTag = 12386312;
pub const anon11541_AudioChannelLayoutTag_HOA_ACN_SN3D: ChannelLayoutTag = 12451840;
pub const anon11541_AudioChannelLayoutTag_HOA_ACN_N3D: ChannelLayoutTag = 12517376;
pub const anon11541_AudioChannelLayoutTag_Atmos_5_1_2: ChannelLayoutTag = 12713992;
pub const anon11541_AudioChannelLayoutTag_Atmos_5_1_4: ChannelLayoutTag = 12779530;
pub const anon11541_AudioChannelLayoutTag_Atmos_7_1_2: ChannelLayoutTag = 12845066;
pub const anon11541_AudioChannelLayoutTag_Atmos_7_1_4: ChannelLayoutTag = 12582924;
pub const anon11541_AudioChannelLayoutTag_Atmos_9_1_6: ChannelLayoutTag = 12648464;
pub const anon11541_AudioChannelLayoutTag_Logic_Mono: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_Logic_Stereo: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_Logic_Quadraphonic: ChannelLayoutTag = 7077892;
pub const anon11541_AudioChannelLayoutTag_Logic_4_0_A: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_Logic_4_0_B: ChannelLayoutTag = 7602180;
pub const anon11541_AudioChannelLayoutTag_Logic_4_0_C: ChannelLayoutTag = 12910596;
pub const anon11541_AudioChannelLayoutTag_Logic_5_0_A: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_Logic_5_0_B: ChannelLayoutTag = 7733253;
pub const anon11541_AudioChannelLayoutTag_Logic_5_0_C: ChannelLayoutTag = 7798789;
pub const anon11541_AudioChannelLayoutTag_Logic_5_0_D: ChannelLayoutTag = 7864325;
pub const anon11541_AudioChannelLayoutTag_Logic_5_1_A: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_Logic_5_1_B: ChannelLayoutTag = 7995398;
pub const anon11541_AudioChannelLayoutTag_Logic_5_1_C: ChannelLayoutTag = 8060934;
pub const anon11541_AudioChannelLayoutTag_Logic_5_1_D: ChannelLayoutTag = 8126470;
pub const anon11541_AudioChannelLayoutTag_Logic_6_0_A: ChannelLayoutTag = 9240582;
pub const anon11541_AudioChannelLayoutTag_Logic_6_0_B: ChannelLayoutTag = 12976134;
pub const anon11541_AudioChannelLayoutTag_Logic_6_0_C: ChannelLayoutTag = 9109510;
pub const anon11541_AudioChannelLayoutTag_Logic_6_1_A: ChannelLayoutTag = 9306119;
pub const anon11541_AudioChannelLayoutTag_Logic_6_1_B: ChannelLayoutTag = 13041671;
pub const anon11541_AudioChannelLayoutTag_Logic_6_1_C: ChannelLayoutTag = 8192007;
pub const anon11541_AudioChannelLayoutTag_Logic_6_1_D: ChannelLayoutTag = 13107207;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_A: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_B: ChannelLayoutTag = 13172744;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_C: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_SDDS_A: ChannelLayoutTag = 8257544;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_SDDS_B: ChannelLayoutTag = 8323080;
pub const anon11541_AudioChannelLayoutTag_Logic_7_1_SDDS_C: ChannelLayoutTag = 8454152;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_5_1_2: ChannelLayoutTag = 12713992;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_5_1_4: ChannelLayoutTag = 12779530;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_7_1_2: ChannelLayoutTag = 12845066;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_7_1_4_A: ChannelLayoutTag = 12582924;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_7_1_4_B: ChannelLayoutTag = 13238284;
pub const anon11541_AudioChannelLayoutTag_Logic_Atmos_7_1_6: ChannelLayoutTag = 13303822;
pub const anon11541_AudioChannelLayoutTag_DiscreteInOrder: ChannelLayoutTag = 9633792;
pub const anon11541_AudioChannelLayoutTag_CICP_1: ChannelLayoutTag = 6553601;
pub const anon11541_AudioChannelLayoutTag_CICP_2: ChannelLayoutTag = 6619138;
pub const anon11541_AudioChannelLayoutTag_CICP_3: ChannelLayoutTag = 7405571;
pub const anon11541_AudioChannelLayoutTag_CICP_4: ChannelLayoutTag = 7536644;
pub const anon11541_AudioChannelLayoutTag_CICP_5: ChannelLayoutTag = 7667717;
pub const anon11541_AudioChannelLayoutTag_CICP_6: ChannelLayoutTag = 7929862;
pub const anon11541_AudioChannelLayoutTag_CICP_7: ChannelLayoutTag = 8323080;
pub const anon11541_AudioChannelLayoutTag_CICP_9: ChannelLayoutTag = 8585219;
pub const anon11541_AudioChannelLayoutTag_CICP_10: ChannelLayoutTag = 8650756;
pub const anon11541_AudioChannelLayoutTag_CICP_11: ChannelLayoutTag = 8192007;
pub const anon11541_AudioChannelLayoutTag_CICP_12: ChannelLayoutTag = 8388616;
pub const anon11541_AudioChannelLayoutTag_CICP_13: ChannelLayoutTag = 13369368;
pub const anon11541_AudioChannelLayoutTag_CICP_14: ChannelLayoutTag = 13434888;
pub const anon11541_AudioChannelLayoutTag_CICP_15: ChannelLayoutTag = 13500428;
pub const anon11541_AudioChannelLayoutTag_CICP_16: ChannelLayoutTag = 13565962;
pub const anon11541_AudioChannelLayoutTag_CICP_17: ChannelLayoutTag = 13631500;
pub const anon11541_AudioChannelLayoutTag_CICP_18: ChannelLayoutTag = 13697038;
pub const anon11541_AudioChannelLayoutTag_CICP_19: ChannelLayoutTag = 13762572;
pub const anon11541_AudioChannelLayoutTag_CICP_20: ChannelLayoutTag = 13828110;
pub const anon11541_AudioChannelLayoutTag_Ogg_3_0: ChannelLayoutTag = 9830403;
pub const anon11541_AudioChannelLayoutTag_Ogg_4_0: ChannelLayoutTag = 12124164;
pub const anon11541_AudioChannelLayoutTag_Ogg_5_0: ChannelLayoutTag = 13893637;
pub const anon11541_AudioChannelLayoutTag_Ogg_5_1: ChannelLayoutTag = 13959174;
pub const anon11541_AudioChannelLayoutTag_Ogg_6_1: ChannelLayoutTag = 14024711;
pub const anon11541_AudioChannelLayoutTag_Ogg_7_1: ChannelLayoutTag = 14090248;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_0_E: ChannelLayoutTag = 14155781;
pub const anon11541_AudioChannelLayoutTag_MPEG_5_1_E: ChannelLayoutTag = 14221318;
pub const anon11541_AudioChannelLayoutTag_MPEG_6_1_B: ChannelLayoutTag = 14286855;
pub const anon11541_AudioChannelLayoutTag_MPEG_7_1_D: ChannelLayoutTag = 14352392;
pub const anon11541_AudioChannelLayoutTag_BeginReserved: ChannelLayoutTag = -268435456;
pub const anon11541_AudioChannelLayoutTag_EndReserved: ChannelLayoutTag = -65537;
pub const anon11541_AudioChannelLayoutTag_Unknown: ChannelLayoutTag = -65536;

pub const ChannelDescription = extern struct {
    mChannelLabel: ChannelLabel,
    mChannelFlags: ChannelFlags,
    mCoordinates: objc.Float32,
};

pub const ChannelLayout = extern struct {
    mChannelLayoutTag: ChannelLayoutTag,
    mChannelBitmap: ChannelBitmap,
    mNumberChannelDescriptions: objc.UInt32,
    mChannelDescriptions: ChannelDescription,
};

pub const FormatListItem = extern struct {
    mASBD: StreamBasicDescription,
    mChannelLayoutTag: ChannelLayoutTag,
};

pub const MPEG4ObjectID = i64;
pub const MPEG4ObjectID_Object_AAC_Main: i64 = 1;
pub const MPEG4ObjectID_Object_AAC_LC: i64 = 2;
pub const MPEG4ObjectID_Object_AAC_SSR: i64 = 3;
pub const MPEG4ObjectID_Object_AAC_LTP: i64 = 4;
pub const MPEG4ObjectID_Object_AAC_SBR: i64 = 5;
pub const MPEG4ObjectID_Object_AAC_Scalable: i64 = 6;
pub const MPEG4ObjectID_Object_TwinVQ: i64 = 7;
pub const MPEG4ObjectID_Object_CELP: i64 = 8;
pub const MPEG4ObjectID_Object_HVXC: i64 = 9;

pub const AVAudioInteger = i64;

pub const AVAudioUInteger = u64;

pub const SessionID = objc.uint32_t;

pub const AVAudioSessionErrorCode = AVAudioInteger;
pub const AVAudioSessionErrorCode_None: AVAudioInteger = 0;
pub const AVAudioSessionErrorCode_MediaServicesFailed: AVAudioInteger = 1836282486;
pub const AVAudioSessionErrorCode_IsBusy: AVAudioInteger = 560030580;
pub const AVAudioSessionErrorCode_IncompatibleCategory: AVAudioInteger = 560161140;
pub const AVAudioSessionErrorCode_CannotInterruptOthers: AVAudioInteger = 560557684;
pub const AVAudioSessionErrorCode_MissingEntitlement: AVAudioInteger = 1701737535;
pub const AVAudioSessionErrorCode_SiriIsRecording: AVAudioInteger = 1936290409;
pub const AVAudioSessionErrorCode_CannotStartPlaying: AVAudioInteger = 561015905;
pub const AVAudioSessionErrorCode_CannotStartRecording: AVAudioInteger = 561145187;
pub const AVAudioSessionErrorCode_BadParam: AVAudioInteger = -50;
pub const AVAudioSessionErrorCode_InsufficientPriority: AVAudioInteger = 561017449;
pub const AVAudioSessionErrorCode_ResourceNotAvailable: AVAudioInteger = 561145203;
pub const AVAudioSessionErrorCode_Unspecified: AVAudioInteger = 2003329396;
pub const AVAudioSessionErrorCode_ExpiredSession: AVAudioInteger = 561210739;
pub const AVAudioSessionErrorCode_SessionNotActive: AVAudioInteger = 1768841571;

pub const anon1001 = u32;
pub const anon1001_AVAudioSessionErrorInsufficientPriority: u32 = 561017449;
