// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL NOT BE MAINTAINED.

const std = @import("std");
const objc = @import("objc.zig"); // Objective-C Runtime in zig.

pub const _CGLContextObject = extern struct {};

pub const ContextObj = ?*_CGLContextObject;

pub const _CGLPixelFormatObject = extern struct {};

pub const PixelFormatObj = ?*_CGLPixelFormatObject;

pub const _CGLRendererInfoObject = extern struct {};

pub const RendererInfoObj = ?*_CGLRendererInfoObject;

pub const _CGLPBufferObject = extern struct {};

pub const PBufferObj = ?*_CGLPBufferObject;

pub const _CGLPixelFormatAttribute = enum(u32) {
    kCGLPFAAllRenderers = 1,
    kCGLPFATripleBuffer = 3,
    kCGLPFADoubleBuffer = 5,
    kCGLPFAColorSize = 8,
    kCGLPFAAlphaSize = 11,
    kCGLPFADepthSize = 12,
    kCGLPFAStencilSize = 13,
    kCGLPFAMinimumPolicy = 51,
    kCGLPFAMaximumPolicy = 52,
    kCGLPFASampleBuffers = 55,
    kCGLPFASamples = 56,
    kCGLPFAColorFloat = 58,
    kCGLPFAMultisample = 59,
    kCGLPFASupersample = 60,
    kCGLPFASampleAlpha = 61,
    kCGLPFARendererID = 70,
    kCGLPFANoRecovery = 72,
    kCGLPFAAccelerated = 73,
    kCGLPFAClosestPolicy = 74,
    kCGLPFABackingStore = 76,
    kCGLPFABackingVolatile = 77,
    kCGLPFADisplayMask = 84,
    kCGLPFAAllowOfflineRenderers = 96,
    kCGLPFAAcceleratedCompute = 97,
    kCGLPFAOpenGLProfile = 99,
    kCGLPFASupportsAutomaticGraphicsSwitching = 101,
    kCGLPFAVirtualScreenCount = 128,
    kCGLPFAAuxBuffers = 7,
    kCGLPFAAccumSize = 14,
    kCGLPFAAuxDepthStencil = 57,
    kCGLPFAStereo = 6,
    kCGLPFAOffScreen = 53,
    kCGLPFAWindow = 80,
    kCGLPFACompliant = 83,
    kCGLPFAPBuffer = 90,
    kCGLPFARemotePBuffer = 91,
    kCGLPFASingleRenderer = 71,
    kCGLPFARobust = 75,
    kCGLPFAMPSafe = 78,
    kCGLPFAMultiScreen = 81,
    kCGLPFAFullScreen = 54,
};

pub const PixelFormatAttribute = _CGLPixelFormatAttribute;

pub const _CGLRendererProperty = enum(u32) {
    kCGLRPOffScreen = 53,
    kCGLRPRendererID = 70,
    kCGLRPAccelerated = 73,
    kCGLRPBackingStore = 76,
    kCGLRPWindow = 80,
    kCGLRPCompliant = 83,
    kCGLRPDisplayMask = 84,
    kCGLRPBufferModes = 100,
    kCGLRPColorModes = 103,
    kCGLRPAccumModes = 104,
    kCGLRPDepthModes = 105,
    kCGLRPStencilModes = 106,
    kCGLRPMaxAuxBuffers = 107,
    kCGLRPMaxSampleBuffers = 108,
    kCGLRPMaxSamples = 109,
    kCGLRPSampleModes = 110,
    kCGLRPSampleAlpha = 111,
    kCGLRPGPUVertProcCapable = 122,
    kCGLRPGPUFragProcCapable = 123,
    kCGLRPRendererCount = 128,
    kCGLRPOnline = 129,
    kCGLRPAcceleratedCompute = 130,
    kCGLRPVideoMemoryMegabytes = 131,
    kCGLRPTextureMemoryMegabytes = 132,
    kCGLRPMajorGLVersion = 133,
    kCGLRPRegistryIDLow = 140,
    kCGLRPRegistryIDHigh = 141,
    kCGLRPRemovable = 142,
    kCGLRPRobust = 75,
    kCGLRPMPSafe = 78,
    kCGLRPMultiScreen = 81,
    kCGLRPFullScreen = 54,
    kCGLRPVideoMemory = 120,
    kCGLRPTextureMemory = 121,
};

pub const RendererProperty = _CGLRendererProperty;

pub const _CGLContextEnable = enum(u32) {
    kCGLCESwapRectangle = 201,
    kCGLCESwapLimit = 203,
    kCGLCERasterization = 221,
    kCGLCEStateValidation = 301,
    kCGLCESurfaceBackingSize = 305,
    kCGLCEDisplayListOptimization = 307,
    kCGLCEMPEngine = 313,
    kCGLCECrashOnRemovedFunctions = 316,
};

pub const ContextEnable = _CGLContextEnable;

pub const _CGLGPURestartStatus = enum(u32) {
    kCGLCPGPURestartStatusNone = 0,
    kCGLCPGPURestartStatusCaused = 1,
    kCGLCPGPURestartStatusBlacklisted = 2,
    kCGLCPGPURestartStatusDenied = 2,
};

pub const GPURestartStatus = _CGLGPURestartStatus;

pub const _CGLContextParameter = enum(u32) {
    kCGLCPSwapRectangle = 200,
    kCGLCPSwapInterval = 222,
    kCGLCPDispatchTableSize = 224,
    kCGLCPClientStorage = 226,
    kCGLCPSurfaceTexture = 228,
    kCGLCPSurfaceOrder = 235,
    kCGLCPSurfaceOpacity = 236,
    kCGLCPSurfaceBackingSize = 304,
    kCGLCPSurfaceSurfaceVolatile = 306,
    kCGLCPReclaimResources = 308,
    kCGLCPCurrentRendererID = 309,
    kCGLCPGPUVertexProcessing = 310,
    kCGLCPGPUFragmentProcessing = 311,
    kCGLCPHasDrawable = 314,
    kCGLCPMPSwapsInFlight = 315,
    kCGLCPGPURestartStatus = 317,
    kCGLCPAbortOnGPURestartStatusBlacklisted = 318,
    kCGLCPAbortOnGPURestartStatusDenied = 318,
    kCGLCPSupportGPURestart = 319,
    kCGLCPSupportSeparateAddressSpace = 320,
    kCGLCPContextPriorityRequest = 608,
};

pub const ContextParameter = _CGLContextParameter;

pub const CPContextPriorityRequest = enum(u32) {
    kCGLCPContextPriorityRequestHigh = 0,
    kCGLCPContextPriorityRequestNormal = 1,
    kCGLCPContextPriorityRequestLow = 2,
};

pub const _CGLGlobalOption = enum(u32) {
    kCGLGOFormatCacheSize = 501,
    kCGLGOClearFormatCache = 502,
    kCGLGORetainRenderers = 503,
    kCGLGOUseBuildCache = 506,
    kCGLGOResetLibrary = 504,
    kCGLGOUseErrorHandler = 505,
};

pub const GlobalOption = _CGLGlobalOption;

pub const _CGLOpenGLProfile = enum(u32) {
    kCGLOGLPVersion_Legacy = 4096,
    kCGLOGLPVersion_3_2_Core = 12800,
    kCGLOGLPVersion_GL3_Core = 12800,
    kCGLOGLPVersion_GL4_Core = 16640,
};

pub const OpenGLProfile = _CGLOpenGLProfile;

pub const _CGLError = enum(u32) {
    kCGLNoError = 0,
    kCGLBadAttribute = 10000,
    kCGLBadProperty = 10001,
    kCGLBadPixelFormat = 10002,
    kCGLBadRendererInfo = 10003,
    kCGLBadContext = 10004,
    kCGLBadDrawable = 10005,
    kCGLBadDisplay = 10006,
    kCGLBadState = 10007,
    kCGLBadValue = 10008,
    kCGLBadMatch = 10009,
    kCGLBadEnumeration = 10010,
    kCGLBadOffScreen = 10011,
    kCGLBadFullScreen = 10012,
    kCGLBadWindow = 10013,
    kCGLBadAddress = 10014,
    kCGLBadCodeModule = 10015,
    kCGLBadAlloc = 10016,
    kCGLBadConnection = 10017,
};

pub const Error = _CGLError;

extern "OpenGL" fn CGLSetCurrentContext(ctx: ContextObj) callconv(.C) Error;
pub const setCurrentContext = CGLSetCurrentContext;

extern "OpenGL" fn CGLGetCurrentContext() callconv(.C) ContextObj;
pub const getCurrentContext = CGLGetCurrentContext;

pub const GLbitfield = objc.uint32_t;

pub const GLboolean = objc.uint8_t;

pub const GLbyte = objc.int8_t;

pub const GLclampf = f32;

pub const GLenum = objc.uint32_t;

pub const GLfloat = f32;

pub const GLint = objc.int32_t;

pub const GLshort = objc.int16_t;

pub const GLsizei = objc.int32_t;

pub const GLubyte = objc.uint8_t;

pub const GLuint = objc.uint32_t;

pub const GLushort = objc.uint16_t;

pub const GLvoid = void;

pub const GLchar = i8;

pub const GLcharARB = i8;

pub const GLhandleARB = ?*anyopaque;

pub const GLdouble = f64;

pub const GLclampd = f64;

pub const GLfixed = objc.int32_t;

pub const GLhalf = objc.uint16_t;

pub const GLhalfARB = objc.uint16_t;

pub const GLint64 = objc.int64_t;

pub const __GLsync = extern struct {};

pub const GLsync = ?*__GLsync;

pub const GLuint64 = objc.uint64_t;

pub const GLint64EXT = objc.int64_t;

pub const GLuint64EXT = objc.uint64_t;

pub const GLintptr = objc.intptr_t;

pub const GLsizeiptr = objc.intptr_t;

pub const GLintptrARB = objc.intptr_t;

pub const GLsizeiptrARB = objc.intptr_t;

pub const ShareGroupRec = extern struct {};

pub const ShareGroupObj = ?*ShareGroupRec;

extern "OpenGL" fn CGLGetShareGroup(ctx: ContextObj) callconv(.C) ShareGroupObj;
pub const getShareGroup = CGLGetShareGroup;

pub const _cl_device_id = extern struct {};

pub const cl_device_id = ?*_cl_device_id;

extern "OpenGL" fn CGLGetDeviceFromGLRenderer(rendererID: GLint) callconv(.C) cl_device_id;
pub const getDeviceFromGLRenderer = CGLGetDeviceFromGLRenderer;

pub const anon131 = enum(u32) {
    kCGLRendererGenericID = 131584,
    kCGLRendererGenericFloatID = 132096,
    kCGLRendererAppleSWID = 132608,
    kCGLRendererATIRage128ID = 135168,
    kCGLRendererATIRadeonID = 135680,
    kCGLRendererATIRageProID = 136192,
    kCGLRendererATIRadeon8500ID = 136704,
    kCGLRendererATIRadeon9700ID = 137216,
    kCGLRendererATIRadeonX1000ID = 137472,
    kCGLRendererATIRadeonX2000ID = 137728,
    kCGLRendererATIRadeonX3000ID = 137984,
    kCGLRendererATIRadeonX4000ID = 138240,
    kCGLRendererGeForce2MXID = 139264,
    kCGLRendererGeForce3ID = 139776,
    kCGLRendererGeForceFXID = 140288,
    kCGLRendererGeForce8xxxID = 140800,
    kCGLRendererGeForceID = 141056,
    kCGLRendererVTBladeXP2ID = 143360,
    kCGLRendererIntel900ID = 147456,
    kCGLRendererIntelX3100ID = 147968,
    kCGLRendererIntelHDID = 148224,
    kCGLRendererIntelHD4000ID = 148480,
    kCGLRendererIntelHD5000ID = 148736,
    kCGLRendererMesa3DFXID = 262144,
};

pub const __IOSurface = extern struct {};

pub const IOSurfaceRef = ?*__IOSurface;

extern "OpenGL" fn CGLTexImageIOSurface2D(
    ctx: ContextObj,
    target: GLenum,
    internal_format: GLenum,
    width: GLsizei,
    height: GLsizei,
    format: GLenum,
    @"type": GLenum,
    ioSurface: IOSurfaceRef,
    plane: GLuint,
) callconv(.C) Error;
pub const texImageIOSurface2D = CGLTexImageIOSurface2D;

extern "OpenGL" fn CGLChoosePixelFormat(attribs: ?*PixelFormatAttribute, pix: ?*PixelFormatObj, npix: ?*GLint) callconv(.C) Error;
pub const choosePixelFormat = CGLChoosePixelFormat;

extern "OpenGL" fn CGLDestroyPixelFormat(pix: PixelFormatObj) callconv(.C) Error;
pub const destroyPixelFormat = CGLDestroyPixelFormat;

extern "OpenGL" fn CGLDescribePixelFormat(
    pix: PixelFormatObj,
    pix_num: GLint,
    attrib: PixelFormatAttribute,
    value: ?*GLint,
) callconv(.C) Error;
pub const describePixelFormat = CGLDescribePixelFormat;

extern "OpenGL" fn CGLReleasePixelFormat(pix: PixelFormatObj) callconv(.C) void;
pub const releasePixelFormat = CGLReleasePixelFormat;

extern "OpenGL" fn CGLRetainPixelFormat(pix: PixelFormatObj) callconv(.C) PixelFormatObj;
pub const retainPixelFormat = CGLRetainPixelFormat;

extern "OpenGL" fn CGLGetPixelFormatRetainCount(pix: PixelFormatObj) callconv(.C) GLuint;
pub const getPixelFormatRetainCount = CGLGetPixelFormatRetainCount;

extern "OpenGL" fn CGLQueryRendererInfo(display_mask: GLuint, rend: ?*RendererInfoObj, nrend: ?*GLint) callconv(.C) Error;
pub const queryRendererInfo = CGLQueryRendererInfo;

extern "OpenGL" fn CGLDestroyRendererInfo(rend: RendererInfoObj) callconv(.C) Error;
pub const destroyRendererInfo = CGLDestroyRendererInfo;

extern "OpenGL" fn CGLDescribeRenderer(
    rend: RendererInfoObj,
    rend_num: GLint,
    prop: RendererProperty,
    value: ?*GLint,
) callconv(.C) Error;
pub const describeRenderer = CGLDescribeRenderer;

extern "OpenGL" fn CGLCreateContext(pix: PixelFormatObj, share: ContextObj, ctx: ?*ContextObj) callconv(.C) Error;
pub const createContext = CGLCreateContext;

extern "OpenGL" fn CGLDestroyContext(ctx: ContextObj) callconv(.C) Error;
pub const destroyContext = CGLDestroyContext;

extern "OpenGL" fn CGLCopyContext(src: ContextObj, dst: ContextObj, mask: GLbitfield) callconv(.C) Error;
pub const copyContext = CGLCopyContext;

extern "OpenGL" fn CGLRetainContext(ctx: ContextObj) callconv(.C) ContextObj;
pub const retainContext = CGLRetainContext;

extern "OpenGL" fn CGLReleaseContext(ctx: ContextObj) callconv(.C) void;
pub const releaseContext = CGLReleaseContext;

extern "OpenGL" fn CGLGetContextRetainCount(ctx: ContextObj) callconv(.C) GLuint;
pub const getContextRetainCount = CGLGetContextRetainCount;

extern "OpenGL" fn CGLGetPixelFormat(ctx: ContextObj) callconv(.C) PixelFormatObj;
pub const getPixelFormat = CGLGetPixelFormat;

extern "OpenGL" fn CGLCreatePBuffer(
    width: GLsizei,
    height: GLsizei,
    target: GLenum,
    internalFormat: GLenum,
    max_level: GLint,
    pbuffer: ?*PBufferObj,
) callconv(.C) Error;
pub const createPBuffer = CGLCreatePBuffer;

extern "OpenGL" fn CGLDestroyPBuffer(pbuffer: PBufferObj) callconv(.C) Error;
pub const destroyPBuffer = CGLDestroyPBuffer;

extern "OpenGL" fn CGLDescribePBuffer(
    obj: PBufferObj,
    width: ?*GLsizei,
    height: ?*GLsizei,
    target: ?*GLenum,
    internalFormat: ?*GLenum,
    mipmap: ?*GLint,
) callconv(.C) Error;
pub const describePBuffer = CGLDescribePBuffer;

extern "OpenGL" fn CGLTexImagePBuffer(ctx: ContextObj, pbuffer: PBufferObj, source: GLenum) callconv(.C) Error;
pub const texImagePBuffer = CGLTexImagePBuffer;

extern "OpenGL" fn CGLRetainPBuffer(pbuffer: PBufferObj) callconv(.C) PBufferObj;
pub const retainPBuffer = CGLRetainPBuffer;

extern "OpenGL" fn CGLReleasePBuffer(pbuffer: PBufferObj) callconv(.C) void;
pub const releasePBuffer = CGLReleasePBuffer;

extern "OpenGL" fn CGLGetPBufferRetainCount(pbuffer: PBufferObj) callconv(.C) GLuint;
pub const getPBufferRetainCount = CGLGetPBufferRetainCount;

extern "OpenGL" fn CGLSetOffScreen(
    ctx: ContextObj,
    width: GLsizei,
    height: GLsizei,
    rowbytes: GLint,
    baseaddr: ?*anyopaque,
) callconv(.C) Error;
pub const setOffScreen = CGLSetOffScreen;

extern "OpenGL" fn CGLGetOffScreen(
    ctx: ContextObj,
    width: ?*GLsizei,
    height: ?*GLsizei,
    rowbytes: ?*GLint,
    baseaddr: ?*?*anyopaque,
) callconv(.C) Error;
pub const getOffScreen = CGLGetOffScreen;

extern "OpenGL" fn CGLSetFullScreen(ctx: ContextObj) callconv(.C) Error;
pub const setFullScreen = CGLSetFullScreen;

extern "OpenGL" fn CGLSetFullScreenOnDisplay(ctx: ContextObj, display_mask: GLuint) callconv(.C) Error;
pub const setFullScreenOnDisplay = CGLSetFullScreenOnDisplay;

extern "OpenGL" fn CGLSetPBuffer(
    ctx: ContextObj,
    pbuffer: PBufferObj,
    face: GLenum,
    level: GLint,
    screen: GLint,
) callconv(.C) Error;
pub const setPBuffer = CGLSetPBuffer;

extern "OpenGL" fn CGLGetPBuffer(
    ctx: ContextObj,
    pbuffer: ?*PBufferObj,
    face: ?*GLenum,
    level: ?*GLint,
    screen: ?*GLint,
) callconv(.C) Error;
pub const getPBuffer = CGLGetPBuffer;

extern "OpenGL" fn CGLClearDrawable(ctx: ContextObj) callconv(.C) Error;
pub const clearDrawable = CGLClearDrawable;

extern "OpenGL" fn CGLFlushDrawable(ctx: ContextObj) callconv(.C) Error;
pub const flushDrawable = CGLFlushDrawable;

extern "OpenGL" fn CGLEnable(ctx: ContextObj, pname: ContextEnable) callconv(.C) Error;
pub const enable = CGLEnable;

extern "OpenGL" fn CGLDisable(ctx: ContextObj, pname: ContextEnable) callconv(.C) Error;
pub const disable = CGLDisable;

extern "OpenGL" fn CGLIsEnabled(ctx: ContextObj, pname: ContextEnable, enable: ?*GLint) callconv(.C) Error;
pub const isEnabled = CGLIsEnabled;

extern "OpenGL" fn CGLSetParameter(ctx: ContextObj, pname: ContextParameter, params: ?*GLint) callconv(.C) Error;
pub const setParameter = CGLSetParameter;

extern "OpenGL" fn CGLGetParameter(ctx: ContextObj, pname: ContextParameter, params: ?*GLint) callconv(.C) Error;
pub const getParameter = CGLGetParameter;

extern "OpenGL" fn CGLSetVirtualScreen(ctx: ContextObj, screen: GLint) callconv(.C) Error;
pub const setVirtualScreen = CGLSetVirtualScreen;

extern "OpenGL" fn CGLGetVirtualScreen(ctx: ContextObj, screen: ?*GLint) callconv(.C) Error;
pub const getVirtualScreen = CGLGetVirtualScreen;

extern "OpenGL" fn CGLUpdateContext(ctx: ContextObj) callconv(.C) Error;
pub const updateContext = CGLUpdateContext;

extern "OpenGL" fn CGLSetGlobalOption(pname: GlobalOption, params: ?*GLint) callconv(.C) Error;
pub const setGlobalOption = CGLSetGlobalOption;

extern "OpenGL" fn CGLGetGlobalOption(pname: GlobalOption, params: ?*GLint) callconv(.C) Error;
pub const getGlobalOption = CGLGetGlobalOption;

extern "OpenGL" fn CGLSetOption(pname: GlobalOption, param: GLint) callconv(.C) Error;
pub const setOption = CGLSetOption;

extern "OpenGL" fn CGLGetOption(pname: GlobalOption, param: ?*GLint) callconv(.C) Error;
pub const getOption = CGLGetOption;

extern "OpenGL" fn CGLLockContext(ctx: ContextObj) callconv(.C) Error;
pub const lockContext = CGLLockContext;

extern "OpenGL" fn CGLUnlockContext(ctx: ContextObj) callconv(.C) Error;
pub const unlockContext = CGLUnlockContext;

extern "OpenGL" fn CGLGetVersion(majorvers: ?*GLint, minorvers: ?*GLint) callconv(.C) void;
pub const getVersion = CGLGetVersion;

extern "OpenGL" fn CGLErrorString(@"error": Error) callconv(.C) ?*i8;
pub const errorString = CGLErrorString;
